### ISSUE TITLE
关于修改22（ssh默认端口）

### ISSUE THREAD

**Issue by sityliu** [PGYER/codefever#101]
docker 容器部署的，部署的时候修改了22端口
docker run -d --privileged=true --name codefever -p 8080:80 -p 2222:22 -it pgyer/codefever-community:latest /usr/sbin/init
可以推送代码上去，但是却克隆不了代码
想问一下，现在还不支持修改22端口吗？因为考虑到安全，不开放22端口，是否可以更换其他端口？

**Comment by cubicwork** [comment]
@sityliu  不开放 22 端口的，在使用 git 的 ssh 方式 clone 的时候需要指定端口，具体方式可以参照 git 的文档。 如果 你使用的 docker 镜像在正确制定端口仍然不能连接请参照 #94 提到的解决方案来处理。 如果问题仍然存在 请附上错误截图到此 issue 中，我们安排开发帮您排出问题。
