### ISSUE TITLE
最新Docker无法使用

### ISSUE THREAD

**Issue by cipfs** [PGYER/codefever#104]
部署好，进去看连nginx都没起来

**Comment by cubicwork** [comment]
@cipfs  你使用的是 docker 直接安装 还是 docker compose 安装，启动的时候有没有调整参数，有没有其他报错，如果是。docker 直接安装 privilige 选项没有关闭呢。

**Comment by cipfs** [comment]
Docker 镜像安装 
docker run -d --privileged=true --name codefever -p 80:80 -p 22:22 -it pgyer/codefever-community:latest /usr/sbin/init

**Comment by cubicwork** [comment]
@cipfs 您好，这个镜像的所有版本在 push 之前都是做过测试的，请问您安装 docker 机器的环境能告诉我一下么，我们安排一下测试：vCPU 数量，内存大小，以及操作系统名称和版本。

**Comment by cipfs** [comment]
主机系统 debian11
`5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64`
配置
E3 1230  16G 独立服务器

**Comment by cubicwork** [comment]
@cipfs  好的，我们找性能接近的机器去测试一下。

**Comment by cubicwork** [comment]
@cipfs 您好 你可以尝试使用 docker-compose 方式尝试安装，因为 docker 可能在非 RedHat Linux 系列的发行版会有一些问题。主要是 systemd 方面的兼容问题。
关于 docker-compose 方式，参照：https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/install_via_docker_compose.md

**Comment by cipfs** [comment]
好的
