### ISSUE TITLE
[仅限 docker-compose 方式构建] fix: 合并请求功能：创建时提示创建失败，合并后提示合并失败（实际都成功了）

### ISSUE THREAD

**Issue by IM-Tse** [PGYER/codefever#113]
# 问题描述（关联Issues：#82、#103）

## 1. 创建合并请求失败
创建合并请求时提示创建失败，页面也不刷新

![create_error](https://user-images.githubusercontent.com/45326843/182448713-9ac77f8c-ea9f-4b84-a423-105927a5905c.png)

不管它，点进去上游仓库一看，实际上已经创建成功了，

![image](https://user-images.githubusercontent.com/45326843/182448306-803d3ad3-afce-4569-8695-1fc4c9a9dbd5.png)

## 2. 合并时提示合并失败

![image](https://user-images.githubusercontent.com/45326843/182449235-2a44352b-346d-4515-8e9c-33f6e226018b.png)

不管它，回到合并请求页面查看，实际上已经合并完成了

![image](https://user-images.githubusercontent.com/45326843/182449295-873693ac-f571-4fec-b453-261e4da673ac.png)

# 错误日志示例
```
# cc_notification_content 表
Query error: Field 'nc_updated' doesn't have a default value
Query error: Field 'nc_deleted' doesn't have a default value

# cc_notification_users 表
Query error: Field 'nu_updated' doesn't have a default value
Query error: Field 'nu_deleted' doesn't have a default value
```

# 手动解决方法

1. 进入容器
`$ docker container exec -it codefever /bin/bash`
3. 进入MYSQL
`$ mysql`
5.  #输入下面SQL语句，修改完成后即可正常使用
```sql
use codefever_community;

alter table `cc_notification_content` alter column `nc_updated` set default '0000-00-00 00:00:00';
alter table `cc_notification_content` alter column `nc_deleted` set default '0000-00-00 00:00:00';

alter table `cc_notification_users` alter column `nu_updated` set default '0000-00-00 00:00:00';
alter table `cc_notification_users` alter column `nu_deleted` set default '0000-00-00 00:00:00';
```

**Comment by cubicwork** [comment]
@IM-Tse 您好，我看到了您的改动，请问您使用的 docker 镜像安装还是使用 docker-compose 方式安装呢 ？

**Comment by IM-Tse** [comment]
docker-compose

**Comment by cubicwork** [comment]
@IM-Tse hi docker-compose 使用的是 mysql 数据库，需要修改 SQL MODE 才能正常工作。 具体参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/install_from_scratch.md#8-%E5%AE%89%E8%A3%85-mysqlmariadb-%E6%97%A0%E9%9C%80%E7%BC%96%E8%AF%91-%E9%95%9C%E5%83%8F%E6%BA%90%E5%AE%89%E8%A3%85 。
