### ISSUE TITLE
e.commit.sha is null 

### ISSUE THREAD

**Issue by kalaGN** [PGYER/codefever#115]
提交并推送一次大量文件 650+ 后，登录后台查看仓库页面空白，控制台报错两个错误e.commit.sha is null  
位置在 /static/js/[1.21a642aa.chunk.js:2:747699](http://ip/port/static/js/1.21a642aa.chunk.js)

**Comment by cubicwork** [comment]
@kalaGN 我们先尝试排查一下错误

**Comment by cubicwork** [comment]
@kalaGN 请问你是使用 docker 方式安装 还是 从零开始安装 的方式安装的 codefever。 我们检查得知您当前前端文件的版本比较低 （2022-03-16），可能我们后续已经修复此错误。我们建议您更新一下 CodeFever 进行一下尝试。具体更新方法请参照：
https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/update.md  我们推荐您在更新之前对重要数据做好备份。

**Comment by kalaGN** [comment]
docker 方式安装的

**Comment by kalaGN** [comment]
@cubicwork  docker 方式安装的

**Comment by cubicwork** [comment]
@kalaGN 你可以先尝试更新一下你的系统  之前回复尝试更新一下系统 看看问题是否存在

**Comment by kalaGN** [comment]
升级完清缓存好了  非常感谢。  @cubicwork
