### ISSUE TITLE
邮件系统用不了

### ISSUE THREAD

**Issue by DAMYSDS** [PGYER/codefever#122]
邮件系统用不了，无法接收邮件

**Comment by cubicwork** [comment]
@DAMYSDS 您好，您需要首先查看你的服务器是否有出网络 25 端口的权限。目前大部分运营商都未打开 25 端口权限；其次，您需要对您的发件ip和用户地址做一下 mx 解析和 txt 解析。具体可以参照 #76 和 #51 中的描述进行设置即可。如果问题不能解决请回复此 issue。
