### ISSUE TITLE
Docker 启动失败

### ISSUE THREAD

**Issue by guiyunweb** [PGYER/codefever#124]
## 服务器配置
![WechatIMG15](https://user-images.githubusercontent.com/77946796/186731236-8141fd3e-8540-407b-ab82-a52722551fab.jpeg)

## docker 版本
![WechatIMG16](https://user-images.githubusercontent.com/77946796/186731382-d120472a-3b74-48d8-81c2-7588532e3248.jpeg)

## 启动命令
![WechatIMG17](https://user-images.githubusercontent.com/77946796/186731414-192b9733-934b-4ff2-8254-57357507f8c7.jpeg)

```
root@debian:~# docker run -d --privileged=true --name codefever -p 10080:80 -p 10022:22 -it pgyer/codefever-community:latest /usr/sbin/init
f4d755253ff973de501e684de9a89aa07e1f639bb3aa18c69396e18ef5ee868e
root@debian:~# docker logs -f f4
[!!!!!!] Failed to allocate manager object, freezing.
```

你好，我使用docker启动失败，日志打印 `Failed to allocate manager object, freezing.`

**Comment by huahuacn** [comment]
同问，NAS使用docker部署，但是不提供privileged权限，请问有没有办法绕过这个权限

**Comment by cubicwork** [comment]
@guiyunweb 这可能是 systemd 的问题，检查一下宿主机有没有安装 systemd。如果没有请参照 从零开始安装的方式安装 或者尝试 去掉 --privileged=true 选项后手动进入 doocker 容器中启动服务。 具体详见 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/admin/dashboard.md#%E7%B3%BB%E7%BB%9F%E6%9C%8D%E5%8A%A1%E7%8A%B6%E6%80%81%E5%8F%8A%E7%BB%B4%E6%8A%A4
@guiyunweb 你也可以参照上述解决方案
