### ISSUE TITLE
镜像功能

### ISSUE THREAD

**Issue by khose-ie** [PGYER/codefever#126]
请问是否可以支持镜像功能呢？将一个仓库作为远程仓库的镜像，每个一段时间自动从远程同步。

**Comment by cubicwork** [comment]
@khose-ie 目前不支持，只能自己在本地创建一个仓库，设置远端仓库为一个新的 remote 然后手动 pull 去同步。

**Comment by khose-ie** [comment]
感谢您的回复，能否考虑支持者这个功能呢

**Comment by cubicwork** [comment]
@khose-ie 目前我们还没有计划要支持这个功能。 如果你打算二次开发，可以尝试自己开发这样的功能。
