### ISSUE TITLE
webhook不触发，查看记录也没有

### ISSUE THREAD

**Issue by mcyrj** [PGYER/codefever#127]
webhook不触发，查看记录也没有

**Comment by cubicwork** [comment]
@mcyrj   您好，请访问 /admin 确认是否所有服务都已经启动。

**Comment by mcyrj** [comment]
docker-compose启动的程序。没有报错。后台有sendmail和crond没有启动。其他的都是正常的

**Comment by cubicwork** [comment]
@mcyrj 你需要登录到 shell 里面手动启动 sendmail 和 crond 服务，crond 服务控制着 webhook 发送。 具体参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/admin/dashboard.md

**Comment by mcyrj** [comment]
好的。谢谢

**Comment by mcyrj** [comment]
docker容器里是不是没有安装crond服务

**Comment by cubicwork** [comment]
> docker容器里是不是没有安装crond服务

容器中应该包含了 crond 服务，如果没有的话，你可能需要手动那装。 试过使用 docker 镜像安装，我们自带镜像中肯定是包含 crond 服务的，详细：https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/install_via_docker.md
