### ISSUE TITLE
webhook X-CodeFever-Signature 的内容验证

### ISSUE THREAD

**Issue by AtWhuhu** [PGYER/codefever#128]
md5({$payload} + {$secret});

源代码中PHP json_encode(payload) 与nodejs 的JSON.stringify(payload) 返回的字符串不一致

我的服务端为nodejs

```javascript
import crypto from 'crypto'
console.log(crypto.createHash('md5').update(`${JSON.stringify(payload)}${screct}`).digest('hex'))
```
md5结果与请求头中的md5不一致

是否可以处理一下？

[stackoverflow的问题](https://stackoverflow.com/questions/35156822/is-javascripts-json-stringfy-the-same-as-phps-json-encode)

**Comment by cubicwork** [comment]
@AtWhuhu hi 您的情况我了解了 我们建议你先暂时不做请求真实性验证，待我们检查后给你一个答复。

**Comment by cubicwork** [comment]
@AtWhuhu  我们已经安排工程师检查了您所说的问题：按照文档的的描述，`X-CodeFever-Signature` `Header` 的值为 `md5=md5({$payload} + {$secret})` 其中 `$payload` 是表示 `response` 中的 `response body` 中的内容，您应该直接使用 `response body` 来进行验证，而不是将其 `parse` 成 `object` 再去 `stringify` 后再去验证。 建议您参照您的 `http 请求库`，获取原始的 `response body` （应该是一个二进制流）然后和 `$secret` 连接以后再进行 `md5` 计算验证。

**Comment by cubicwork** [comment]
我们这边相关代码位于 https://github.com/PGYER/codefever/blob/master/application/controllers/backend/repository_webhook.php#L54-L90 计算 `md5` 时的入参和发送 `response` 是使用的是同一个字符串。验证时只需要验证 `resposne body` 即可。

**Comment by AtWhuhu** [comment]
> @AtWhuhu 我们已经安排工程师检查了您所说的问题：按照文档的的描述，`X-CodeFever-Signature` `Header` 的值为 `md5=md5({$payload} + {$secret})` 其中 `$payload` 是表示 `response` 中的 `response body` 中的内容，您应该直接使用 `response body` 来进行验证，而不是将其 `parse` 成 `object` 再去 `stringify` 后再去验证。 建议您参照您的 `http 请求库`，获取原始的 `response body` （应该是一个二进制流）然后和 `$secret` 连接以后再进行 `md5` 计算验证。

我使用express 库自带的bodyParser.json()处理了，现在用原始二进制验证一致了。问题已解决，谢谢
