### ISSUE TITLE
能否提供一个修改ssh url的功能

### ISSUE THREAD

**Issue by dnslin** [PGYER/codefever#132]
我看到后台能设置 主机 > URL 
但是这里的默认 ssh url就是 https://xx.abc.com 后的 xxx.abc.com

能否像 gitea一样进行分开设置

**Comment by cubicwork** [comment]
@dnslin 已经修改，我们会在最近的更新中带上此次修改。 如何更新参照：https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/update.md
