### ISSUE TITLE
找回密码功能存在潜在安全风险

### ISSUE THREAD

**Issue by q112008221** [PGYER/codefever#135]
在用户请求找回密码时，会以电子邮箱地址为输入，使用TOTP算法生成找回密码需要的邮箱验证码。在默认配置的情况下，TOTP算法使用默认密钥。

攻击者可以使用默认密钥重复此过程，计算任意一个账户找回密码需要的邮箱验证码，进而获取任意一个用户的登录权限。

详见https://github.com/q112008221/CodeFever-Community-Edition-Vulnerability

**Comment by cubicwork** [comment]
@q112008221  感谢您的提示，我们会在最近的更新修补此问题。
