### ISSUE TITLE
关于docker部署外部挂载的问题

### ISSUE THREAD

**Issue by 203579397** [PGYER/codefever#138]
请问 仓可配置 、注册的用户信息、  代码仓库 目录在哪？
总不能docker容器已重启 存的代码、配置、用户都没了

**Comment by cubicwork** [comment]
@203579397 你可以尝试从零开始安装 或者尝试 docker-compose 的版本。
具体参照 https://github.com/PGYER/codefever/tree/master/doc/zh-cn/installation
