### ISSUE TITLE
windows server是否能够支持？

### ISSUE THREAD

**Issue by 613783237** [PGYER/codefever#145]
市面上的大多数都是Linux平台的，我们这个是否支持windows server安装，如果能安装，可以弄个教程吗？本地环境windows server比较方便一些，还可以在本机搭建

**Comment by cubicwork** [comment]
widnows server 可以支持，但是需要你需要有比较强的服务端能力。可以参照 从零开始安装 在 Windows Server 上安装 CodeFever。 祝你好运，如果遇到问题回复此 Issue 即可。

**Comment by cubicwork** [comment]
@613783237 理论上可以在 Windows 上面安装，因为 CodeFever 运行依赖的环境 Windows Server 都支持
