### ISSUE TITLE
[建议]增加具体的SMTP服务器配置

### ISSUE THREAD

**Issue by daoyui** [PGYER/codefever#146]
建议增加具体的SMTP邮件服务器配置，例如地址、端口、账号信息等

**Comment by cubicwork** [comment]
@daoyui 您好，关于 SMTP 服务器配置请参照文档 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/admin/settings.md#smtp 或 #142 中的解答来进行。

**Comment by daoyui** [comment]
好的，谢谢您
