### ISSUE TITLE
可以自定义角色和设置该角色的菜单访问权限吗？

### ISSUE THREAD

**Issue by tony2y** [PGYER/codefever#148]
1.比如限制该角色访问成员列表
2.比如限制该角色创建新仓库或仓库组

**Comment by cubicwork** [comment]
@tony2y 你可以为成员设置角色，角色的权限目前是固定不变的不支持修改，具体参照： https://github.com/PGYER/codefever/blob/master/doc/zh-cn/repo/members.md
