### ISSUE TITLE
配合Jenkins使用WebHooks自动化部署代码问题

### ISSUE THREAD

**Issue by yifunxxx** [PGYER/codefever#149]
在使用 **jenkins** 中插件 **Generic Webhook Trigger Plugin** 用来接受推送代码触发事件时
**codefever** 发送的请求头中会有两个参数，分别是`Request URL`和`Request method`
如下图：
![image](https://user-images.githubusercontent.com/57654452/233761588-f1eca09a-0afd-4ea1-b500-d0a7714f0f15.png)
得到的响应如下图：
![image](https://user-images.githubusercontent.com/57654452/233761612-66f2025b-c614-4b2d-8ddd-c0982dba52a2.png)
如上图，响应失败的原因是请求中包含了非法的字符 空格
我大致看了下请求，觉得可能是请求头中的这两个参数的问题，因为请求头的key应该是不能有空格的
我修改源码，经过测试发现，删除头部这两个参数之后，hooks成功了，jenkins如期进行了自动部署，如下图：
![image](https://user-images.githubusercontent.com/57654452/233761822-1f7e163a-8420-4938-aa38-95758a50487e.png)
![image](https://user-images.githubusercontent.com/57654452/233761835-86a0e6db-ab5a-41e7-9a93-a26e437a09c0.png)
我修改的部分源码如下图：
![image](https://user-images.githubusercontent.com/57654452/233761869-6c2c5ced-f0d7-4be5-9950-0602ae837a03.png)

**Comment by cubicwork** [comment]
@yifunxxx 感谢你的反馈，这两个请求头本不应该存在于 request header，包含空格本身也不符合 HTTP 规范会导致部分 HTTP 协议解析器产生错误。我们会在随后的更新修正此问题。
