### ISSUE TITLE
请问怎么删除用户

### ISSUE THREAD

**Issue by mose-zm** [PGYER/codefever#151]
如题，请问怎么删除用户
禁用后，9001认证需要查这些数据，离职的人员必须删除才行，请问怎么删除。。。

**Comment by cubicwork** [comment]
@mose-zm 您需要手动链接数据库清除，codefever-community 使用 mariadb 数据库管理用户数据，你需要登录 mariadb 控制台（如果是 docker 安装需要提前登录docker shell），在 `codefever_community` 库中找到 `cc_users` 表，删除相应记录即可。 数据库默认用户名为 `root` 默认密码是 `123456`。 如果还有问题直接回复此 issue 即可。
