### ISSUE TITLE
提交的图片和Markdown文件的图片无法正常显示

### ISSUE THREAD

**Issue by wenjia03** [PGYER/codefever#152]
如图，提交上来的图片无法正常显示
![image](https://github.com/PGYER/codefever/assets/25656832/214a5d7f-5dc5-4ebf-a7e8-15488456435c)
![image](https://github.com/PGYER/codefever/assets/25656832/8f99df28-6ede-4cea-b052-e91bbde73ab3)
![image](https://github.com/PGYER/codefever/assets/25656832/b00ca7d6-bc35-4019-a529-329d06bce0bd)
无论是png\jpg\jpeg，相对路径或同目录下，均无法解析

**Comment by cubicwork** [comment]
@wenjia03 您好，CodeFever 在设计的时候就不允许直接下载 二进制文件，因此在 md 中引用媒体文件可能不会正常显示。
