### ISSUE TITLE
docker容器配置sql的环境变量不生效

### ISSUE THREAD

**Issue by baigem** [PGYER/codefever#154]
如题，我查看了docker-compose.yml文件中的配置，发现可以通过配置环境变量如DB_USER等来指定db数据库的配置，但是我配置后并没有生效，只有进入容器内部，手动编辑配置文件后才行，请问现在是还不支持通过变量来配置数据库吗？

**Comment by cubicwork** [comment]
@baigem 目前是的，你可以按照自己的喜好参照从头开始安装文档构建自己的镜像
