### ISSUE TITLE
迁移服务导致的push失败

### ISSUE THREAD

**Issue by baigem** [PGYER/codefever#155]
如题，我把服务迁移到另一台服务器，备份了数据库和存储库，部署好后git拉取代码没有问题，但是push的时候就报错了，以下是错误报告

remote: PHP Warning:  yaml_parse_file(/data/www/codefever-community/git-storage/env.yaml): failed to open stream: No such file or directory in /data/www/codefever-community/git-storage/2ff5b8019f0df88c8ebad1576f5a09cb/hooks/pre-receive on line 3
remote: PHP Notice:  Trying to access array offset on value of type bool in /data/www/codefever-community/git-storage/2ff5b8019f0df88c8ebad1576f5a09cb/hooks/pre-receive on line 5
remote: [CodeFever Community]: Bad configuration, Contact site administrator if operation rejected!.

**Comment by cubicwork** [comment]
@baigem hi 你先确认报错的文件是否存在，这个文件可能是一个软连接，保证软连接能链接到正常文件问题应该可以解决。如果有问题可以继续回复此 issue
