### ISSUE TITLE
容器目录映射失败

### ISSUE THREAD

**Issue by SlienceH** [PGYER/codefever#156]
你们好，我想在修改映射端口的同时也进行目录的映射，我这样执行一直是访问不了项目的，有懂的兄弟帮忙看看，该如何修改吗
docker run -d --privileged=true --name codefever -p 9001:80 -p 23:22 -p 3307:3306 -v /www/wwwroot/codefever:/data -it pgyer/codefever-community:latest /usr/sbin/init

**Comment by cubicwork** [comment]
@SlienceH hi, /data 目录包含了所有的项目文件，直接映射到 docker 外面的空目录上会导致server无法访问项目中的任何文件，因此会出现不能访问的情况。如果你希望创建自已的docker镜像允许自己单独管理 git 文件和 数据库文件，请参照从零开始安装文档，直接重新构建镜像。注意 git-storage / file-storage / emv.yaml / config.yaml 以及数据库连接都需要映射出来。在 docker 启动的时候执行 install.sh 脚本初始化上述目录，运行 create_db.sh 初始化数据库。即可。

**Comment by cubicwork** [comment]
@SlienceH 你现在可以参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/install_via_docker.md 的操作来映射目录了。
