### ISSUE TITLE
Doc for install in Windows server

### ISSUE THREAD

**Issue by angelofan** [PGYER/codefever#16]
I can't find any documentation on how to install to a Windows server.

If codefever supports windows server, please add installation documentation.

**Comment by cubicwork** [comment]
> I can't find any documentation on how to install to a Windows server.
> 
> If codefever supports windows server, please add installation documentation.

installation pressure on windows server is under test. the docs will be released soon.

**Comment by shishirui** [comment]
Another option is that you can install docker on windows first and then install codefever in docker.

**Comment by cubicwork** [comment]
@angelofan  you can run codefever on docker. see https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/install_via_docker.md for details.

**Comment by angelofan** [comment]
Docker要安装到Windows server必须要先安装Docker Toolbox，然而Docker Toolbox停止维护了，提示要安装Docker Enterprise Engine。然后Docker Enterprise Engine有对系统版本的严格限制，即Windows Server 2016 和 Windows Server 2019，并不支持Windows server 2012R2。

对于不了解Docker的人来说，要想成功安装codefever还是要花点时间的。所以还是建议codefever有直接的安装程序。

在我的项目中不会用到Docker，为了安装codefever，我现在必须开始了解Docker。这增加了上手难易程度。

**Comment by cubicwork** [comment]
@angelofan 你好，Windows Server 2019 以上的操作系统已经开始支持 WSL，您可以为您的 Windows Server 打开 WSL 功能，在 WSL 上直接使用 docker。你可以使用 Ubuntu 作为 WSL系统  参照：https://docs.microsoft.com/zh-cn/windows/wsl/install-on-server。如果以上方式不能满足你的需求，请关注我们随后计划发布的 widnows 安装文档。
