### ISSUE TITLE
Docker安装持久化问题

### ISSUE THREAD

**Issue by aboutyj** [PGYER/codefever#17]
看文档发现没有创建卷，docker run后也没挂载卷或本地目录，内部目录是否可以出个说明，需要挂载到哪个目录才能实现持久化

**Comment by cubicwork** [comment]
你好，我们不推荐在 `docker` 上建立卷，因为可能会存在一些 `hooks` 映射的问题。如果你需要备份您的 `git` 仓库，所有的 `git` 仓库都存在于 `/data/www/git-storage` 目录下。
