### ISSUE TITLE
error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413

### ISSUE THREAD

**Issue by fengyexin9** [PGYER/codefever#176]
error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
 
git push 的时候出现上面问题

**Comment by cubicwork** [comment]
@fengyexin9  您好，你已经在 service@pgyer.com 邮箱中报告过此问题，我们已经在邮箱中进行了回复。 内容为：

```
您好：
    HTTP 413 错误是请求体过大的错误。你可以检查您的 nginx 配置，调整 Request Body 大小的限制。
详细可以参照这个链接 https://zhuanlan.zhihu.com/p/405776683 。感谢使用 CodeFever。

如果你需要配置 HTTPS SSL 证书可以使用 nginx 转发 443 到 docker 80 端口上
如果你需要 SSH 服务只需 docker 22 端口直接绑定到宿主机需要的端口上即可不需要 nginx 做代理。
```

如果此回复不能解决您的问题，请回复邮件或回复此 issue。 如果此回复可以解决您的问题，请关闭此 issue

**Comment by fengyexin9** [comment]
目前使用了 ip + 端口 进行拉取项目，成功拉取，但是提交文件还是出现413和22的问题



枫叶
***@***.***








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PGYER/codefever"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 中午12:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PGYER/codefever] error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413 (Issue #176)





 
@fengyexin9  您好，你已经在 ***@***.*** 邮箱中报告过此问题，我们已经在邮箱中进行了回复。 内容为：
 您好：     HTTP 413 错误是请求体过大的错误。你可以检查您的 nginx 配置，调整 Request Body 大小的限制。 详细可以参照这个链接 https://zhuanlan.zhihu.com/p/405776683 。感谢使用 CodeFever。 如果你需要配置 HTTPS SSL 证书可以使用 nginx 转发 443 到 docker 80 端口上 如果你需要 SSH 服务只需 docker 22 端口直接绑定到宿主机需要的端口上即可不需要 nginx 做代理。  
如果此回复不能解决您的问题，请回复邮件或回复此 issue。 如果此回复可以解决您的问题，请关闭此 issue

**Comment by cubicwork** [comment]
@fengyexin9 你提交的文件有多大呢，你是指 push 的时候会报 413 错误么，首先 你的仓库有多大呢，push 的文件有多大呢。如果你 push 的单个文件很大的话，你需要按照之前给你的链接设置 nginx。 先设置你的转发的 nginx 调整 client_max_body_size ，超过你的单个文件尺寸。 然后登录 docker 在 /usr/local/nginx 里面做同样的设置调整 client_max_body_size 即可。

**Comment by fengyexin9** [comment]
我现在使用的是 ip + 端口 进行push的，我的文件夹 + .git文件 总共15M，push的时候 出现的 413 和 22






枫叶
***@***.***








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PGYER/codefever"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PGYER/codefever] error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413 (Issue #176)





 
@fengyexin9 你提交的文件有多大呢，你是指 push 的时候会报 413 错误么，首先 你的仓库有多大呢，push 的文件有多大呢。如果你 push 的单个文件很大的话，你需要按照之前给你的链接设置 nginx。 先设置你的转发的 nginx 调整 client_max_body_size ，超过你的单个文件尺寸。 然后登录 docker 在 /usr/local/nginx 里面做同样的设置调整 client_max_body_size 即可。

**Comment by cubicwork** [comment]
@fengyexin9 不使用 nginx 转发 http 服务 直接用 docker 放出来的端口作为 http 服务有这样的问题么？

**Comment by fengyexin9** [comment]
有这样的问题的（docker 部署后：使用ip+端口 push出现同样的问题）

**Comment by cubicwork** [comment]
> @fengyexin9 你提交的文件有多大呢，你是指 push 的时候会报 413 错误么，首先 你的仓库有多大呢，push 的文件有多大呢。如果你 push 的单个文件很大的话，你需要按照之前给你的链接设置 nginx。 先设置你的转发的 nginx 调整 client_max_body_size ，超过你的单个文件尺寸。 然后登录 docker 在 /usr/local/nginx 里面做同样的设置调整 client_max_body_size 即可。

@fengyexin9 那你先按照这样的思路去修改一下配置，看看问题能解决么。 我们这边没有办法复现出相同的情况。

**Comment by fengyexin9** [comment]
我自己的文件是10M， 而.git 差不多有5M， docker 容器中的 nginx的 client_max_body_size&nbsp; 有配置为150m









枫叶
***@***.***







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PGYER/codefever"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PGYER/codefever] error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413 (Issue #176)





  
@fengyexin9 你提交的文件有多大呢，你是指 push 的时候会报 413 错误么，首先 你的仓库有多大呢，push 的文件有多大呢。如果你 push 的单个文件很大的话，你需要按照之前给你的链接设置 nginx。 先设置你的转发的 nginx 调整 client_max_body_size ，超过你的单个文件尺寸。 然后登录 docker 在 /usr/local/nginx 里面做同样的设置调整 client_max_body_size 即可。
  
@fengyexin9 那你先按照这样的思路去修改一下配置，看看问题能解决么。 我们这边没有办法复现出相同的情况。

**Comment by cubicwork** [comment]
@fengyexin9  用微信扫描这个二维码吧，咱们私聊，你的情况可能比较特殊，我可能需要一些敏感信息
 
![IMG_3707](https://github.com/PGYER/codefever/assets/9900088/91e0b781-7bc7-4242-95b9-76c218720c4f)

**Comment by fengyexin9** [comment]
谢谢，我进入 了docker部署的codefever 容器中 配置了/etc/nginx/nginx.conf 设置client_max_body_size 150m; 现在正常push了，非常感谢



枫叶
***@***.***








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PGYER/codefever"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PGYER/codefever] error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413 (Issue #176)





 
@fengyexin9  用微信扫描这个二维码吧，咱们私聊，你的情况可能比较特殊，我可能需要一些敏感信息
