### ISSUE TITLE
关于功能建议

### ISSUE THREAD

**Issue by ytqiao3** [PGYER/codefever#177]
1. 我该怎样创建一个分支保护规则，用于每一个从master 创建的非 test和dev分支呢。
2. 现在我有三个分支master(生产)、test(测试)、dev(开发)，开发人员从master拉取分支xx-yy进行需求开发，但是xx-yy不允许test和dev向自己合并。我想创建一个规则默认用在所有的新创建的分支上。

**Comment by cubicwork** [comment]
@ytqiao3 您好，目前 codefever 不能创建全局的分支保护规则，只能针对于每一个仓库特定的分支进行设置。对于单一仓库，可以使用正则表达式作为分支名，来进行设置，以匹配全部分支或者符合某些特定命名规则的分支。按照你的情况你可以尝试 `/^(^(dev)|(master))$/g` 来作为分支名进行设置。
