### ISSUE TITLE
k8s 环境下无法访问

### ISSUE THREAD

**Issue by iotopo** [PGYER/codefever#178]
访问首页根目录，浏览器显示 HTTP ERROR 500。
访问 curl http://hostname/index.html 可以显示内容。

**Comment by iotopo** [comment]
容器日志最后显示：
`
=== IMPORTANT NOTICE ===
1. Codefever community version is installed.
2. Type http://127.0.0.1 OR http://<server ip> to login.
3. Default login email: root@codefever.cn, password: 123456 .
/data/www/codefever-community
`

**Comment by cubicwork** [comment]
@iotopo 你使用的是哪种安装方式，docker 镜像还是 docker-compose ？

**Comment by iotopo** [comment]
@cubicwork 是在 k8s 环境部署的，用的是华为云CCE，使用的是 docker 镜像最新版本

**Comment by cubicwork** [comment]
@iotopo 登录到 docker 镜像上会重新启动一下服务吧。 详细参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/admin/dashboard.md

**Comment by iotopo** [comment]
> @iotopo 登录到 docker 镜像上会重新启动一下服务吧。 详细参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/admin/dashboard.md

按照这个方式手动启动过 docker 内的服务，但是没有效果

**Comment by iotopo** [comment]
![image](https://github.com/PGYER/codefever/assets/89469406/a77ed324-cd29-4365-98b5-f806e265d57f)
codefever 的服务启动不起来

**Comment by iotopo** [comment]
sh-4.2# service conrd start     
Redirecting to /bin/systemctl start conrd.service
Failed to start conrd.service: Unit not found.

**Comment by cubicwork** [comment]
@iotopo 我感觉问题应该大概率出在 k8s 上， docker 最新版本需要 --privileged=true 才能启动服务。如果 --privileged=true 已经设置，请尝试将容器的宿主操作系统更换为 CentOS。如果以上工作都做了还没有达到效果，你可以尝试在华为云的 1C1G 的 ECS 尝试部署最新的 Docker 镜像，对比和 k8s 部署上的差距从而找到原因。/
docker 镜像部署参考：https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/install_via_docker.md
如果还有问题你可以继续回复此 Issue

**Comment by iotopo** [comment]
已经设置了privileged=true 的
![image](https://github.com/PGYER/codefever/assets/89469406/2a2a9be2-0d4d-4e06-8d79-54335b4fae25)

**Comment by iotopo** [comment]
单独运行 docker 是可以的，这个我试过，但在 k8s上运行就会有这个问题

**Comment by iotopo** [comment]
请问有没有地方可以查看服务无法启动的原因呢？logs 里没有内容，其它地方有日志可以查询吗？

**Comment by cubicwork** [comment]
@iotopo 你可以查看下 /data/www/codefever-community/application/logs 通常这个目录会被暴露出来。然后检查一下容器的 logs。 你遇到的情况我建议先从 nginx 开始检查。 /usr/local/nginx/ 目录下可以看到 nginx 的 error log。

**Comment by iotopo** [comment]
![image](https://github.com/PGYER/codefever/assets/89469406/4f37ab33-dbf3-45ae-a285-9ea39c850e63)
看起来像是映射的目录权限有问题
