### ISSUE TITLE
关于登录上去仓库转圈圈的问题

### ISSUE THREAD

**Issue by Yiersanxu** [PGYER/codefever#179]
维护的服务器某个账号登录上去后，**Web页面显示的仓库都在转圈圈，点击所有、点击我参与的、点击我创建的都在转圈圈；**
能够修改个人信息，修改用户名以及邮箱，能够保存且数据正常，我尝试修改了密码和邮箱，退出去后使用修改后的能够正常使用；
切换别的IP访问进行登录同个账号，能登录进去，也是上述转圈圈，使用手机流量登录也是转圈圈；
切换了别的账号之后全部正常，就该账号不行；

使用中的小缺陷，进去后台看不了用户密码select * from codefever_community.cc_users，账号对应的 u_password  的值是登录不上去的 ;以及部署的时候是docker部署的尝试升级，进去容器后，cd /data/www/codefever-community  git pull origin master 拉取不了，等了5分钟我手动中断了，机子在海外6月末部署的
目前想将仓库迁移掉，是否有迁移的文档，以及对mysql迁移的常见方案是否能适用

希望给予答复，非常感谢

**Comment by cubicwork** [comment]
@Yiersanxu 您好直接查库库中的 u_password 是不能经过散列计算的值不能直接用来登录，登录之后整个仓库都在转圈可能是 PHP 服务器没有启动，请查看一下是都所有服务都已经启动。具体参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/admin/dashboard.md 使用管理界面或者在命令行查看服务状态。如果还有疑问请回复此 issue。如果忘记管理员密码，请将管理员 u_password 字段修改成 14e1b600b1fd579f47433b88e8d85291 然后使用 123456 来登录。

**Comment by Yiersanxu** [comment]
issue

**Comment by Yiersanxu** [comment]
![image](https://github.com/PGYER/codefever/assets/141145691/cd29269e-6b7a-4877-ac85-9068e413c5fb)

[root@a5af84db8278 codefever-community]# service php-fpm status
php-fpm (pid 3178) is running...
[root@a5af84db8278 codefever-community]# service php-fpm reload
Reload service php-fpm  done


我刚刚进入查看了一下状态是正常的，我之前所有服务都重启过了，现在重启了，登录那个账号还是有问题，还是如图，就只有那个账号有问题

**Comment by Yiersanxu** [comment]
> @Yiersanxu 您好直接查库库中的 u_password 是不能经过散列计算的值不能直接用来登录，登录之后整个仓库都在转圈可能是 PHP 服务器没有启动，请查看一下是都所有服务都已经启动。具体参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/admin/dashboard.md 使用管理界面或者在命令行查看服务状态。如果还有疑问请回复此 issue。如果忘记管理员密码，请将管理员 u_password 字段修改成 14e1b600b1fd579f47433b88e8d85291 然后使用 123456 来登录。
issue

**Comment by cubicwork** [comment]
@Yiersanxu 那你现在遇到的问题比较复杂，你留一个邮箱吧，我给你发个二维码，你微信加一下，我需要了解一些机密信息。

**Comment by Yiersanxu** [comment]
987397600@qq.com

> @Yiersanxu 那你现在遇到的问题比较复杂，你留一个邮箱吧，我给你发个二维码，你微信加一下，我需要了解一些机密信息。

**Comment by cubicwork** [comment]
问题已经解决
