### ISSUE TITLE
Docker镜像安装遇到问题

### ISSUE THREAD

**Issue by ljbf-dao** [PGYER/codefever#183]
按照教程拉取镜像启动后，运行 docker container logs codefever -f查看初始化进度疯狂报错
ERROR 2002 (HY000): Can't connect to local server through socket '/var/lib/mysql/mysql.sock' (2)
stty: standard input: Inappropriate ioctl for device
Enter current password for root (enter for none): 
stty: standard input: Inappropriate ioctl for device
似乎是数据库方面的问题，我是否遗漏了哪个环节需要进行配置呢？

**Comment by yerier** [comment]
一样的问题

**Comment by ljbf-dao** [comment]
> 
我折腾了几天，准备试试从零安装了o(╥﹏╥)o

**Comment by ljbf-dao** [comment]
> 一样的问题

兄弟你的宿主机是什么系统？

**Comment by yerier** [comment]
> > 一样的问题
> 
> 兄弟你的宿主机是什么系统？

debian 11

**Comment by ljbf-dao** [comment]
> > > 一样的问题
> > 
> > 
> > 兄弟你的宿主机是什么系统？
> 
> debian 11

我这边已经搞定了，是宿主机的版本太高了，之前我是用Ubuntu的22.04，现在换成20.04拉镜像就正常了，具体问题可以参考https://blog.csdn.net/Fenplan/article/details/118515184

**Comment by yerier** [comment]
> > > > 一样的问题
> > > 
> > > 
> > > 兄弟你的宿主机是什么系统？
> > 
> > 
> > debian 11
> 
> 我这边已经搞定了，是宿主机的版本太高了，之前我是用Ubuntu的22.04，现在换成20.04拉镜像就正常了，具体问题可以参考https://blog.csdn.net/davidemiya/article/details/128222685

谢谢 系统降级，解决问题

**Comment by wynn0123** [comment]
docker run 报 /bin/bash: ./misc/system_init.sh: No such file or directory

**Comment by cubicwork** [comment]
@wynn0123 您好 ./misc/system_init.sh 这个文件是真实存在，请确认您是否使用最近版本的 docker 镜像
