### ISSUE TITLE
系统迁移问题

### ISSUE THREAD

**Issue by ntyouth** [PGYER/codefever#191]
按照数据库及仓库的备份方法备份，在新的服务器上重新部署了系统导入了数据库及仓库目录，打开仓库内容是空的。这个需要如何处理

**Comment by cubicwork** [comment]
@ntyouth   您好，您能详细描述您遇到的情况么？包括你当前的版本，你的部署方式，以及迁移的方式。

**Comment by ntyouth** [comment]
你好，我原系统部署采用的Docker 镜像安装的,版本就是最新版本，数据库的备份参照 https://github.com/PGYER/codefever/issues/47 ，git 仓库的备份参照 https://github.com/PGYER/codefever/issues/17 。新服务器上也是采用的Docker 镜像安装后导入了备份的数据库，git仓库是直接将备份的目录解压到新的Docker 容器的对应目录下的。恢复之后所有用户都可以登录，就是仓库对应不到内容

**Comment by cubicwork** [comment]
@ntyouth 您好，原系统大概是什么时候安装的，那个版本 git 目录是否已经通过 -v 的方式添加进去? r如果是，情尝试做以下检查。
1. 你检查一下 仓库目录里面的文件读取权限是否正确，确认下 docker 是否有权限读取此目录下的文件。
2. 登录 docker 镜像，确认下目录已经被正确挂载。

**Comment by zhangxueyong-emen** [comment]
你好，windows能安装吗？

**Comment by cubicwork** [comment]
@zhangxueyong-emen 您好，Windows 下面需要根据 从零开始安装 文档开始设置。理论上可以安装，但是需要自己摸索。
