### ISSUE TITLE
根据git地址导入项目

### ISSUE THREAD

**Issue by BenYanYi** [PGYER/codefever#194]
能根据git地址来导入项目吗

**Comment by cubicwork** [comment]
@BenYanYi 目前还不能，只能在本地完成导入：

1. git clone <目标仓库地址>
2. 在 CodeFever 上创建一个新的仓库
3. git remote add codefever <刚才查滚件的仓库地址>
4. git push codefever master

**Comment by cubicwork** [comment]
same to #144

**Comment by Linjieqiang** [comment]
项目不维护更新了吗

**Comment by cubicwork** [comment]
@Linjieqiang 您好，目前项目功能已经稳定，处于维护阶段，您是在使用过程中遇到什么问题了么？
