### ISSUE TITLE
ldap集成认证

### ISSUE THREAD

**Issue by captain686** [PGYER/codefever#197]
能否增加ldap集成认证方式

**Comment by cubicwork** [comment]
@captain686 目前还不支持 LDAP 认证方式，你可以参考以下代码自己实现：
新增用户：https://github.com/PGYER/codefever/blob/master/application/controllers/user.php#L167-L174
生成登录凭据(Cookie)：https://github.com/PGYER/codefever/blob/master/application/controllers/user.php#L60
