### ISSUE TITLE
docker运行后mail和cron在后台都显示未启动

### ISSUE THREAD

**Issue by aohun** [PGYER/codefever#199]
进入容器shell执行查看cron状态命令报错
![image](https://github.com/PGYER/codefever/assets/37433539/0d8e3fe8-c328-414a-8fc2-f0cc7217c3f8)

**Comment by cubicwork** [comment]
@aohun  您好 请问您是使用 docker-compose 方式安装的还是直接使用 docker-image 安装的

**Comment by aohun** [comment]
docker-image 安装的

**Comment by cubicwork** [comment]
@aohun  Sorry 我检查了一下我们的文档，是我们的文档出现了问题，正确的命令是 **service crond start** 。对您造成的不便表示抱歉。

**Comment by cubicwork** [comment]
@aohun 详细文档变动可以参阅这个 MR #200

**Comment by aohun** [comment]
执行上述命令仍报错
crond:crondd: ERROR (no such process)
