### ISSUE TITLE
通过docker-compose部署设置没有被持久化

### ISSUE THREAD

**Issue by Ainto** [PGYER/codefever#201]
使用 docker-compose 部署后设置没有被持久化，会在每次重启后丢失设置
![image](https://github.com/user-attachments/assets/e201b909-ae2d-4f40-8e1e-17e5949bc145)

目前持久化了：
/data/www/codefever-community/git-storage
/data/www/codefever-community/application/logs
/var/lib/mysql
翻阅文档也没有这方面的描述，能请问还需要持久化什么目录可以解决此问题呢，谢谢

**Comment by cubicwork** [comment]
@Ainto  您好，您可以参照 https://github.com/PGYER/codefever/blob/master/codefever.build 来修改 docker-compose 配置

**Comment by Ainto** [comment]
> @Ainto 您好，您可以参照 https://github.com/PGYER/codefever/blob/master/codefever.build 来修改 docker-compose 配置

谢谢回复，这情况似乎只在codefever-community-lite镜像中存在

```
# create symbolic link
RUN mkdir -p ./env && chmod -R 0777 ./env 
RUN ln -s ./env/env.yaml ./env.yaml && ln -s ./env/config.yaml ./config.yaml
```
此镜像中此处似乎没有正常工作，而上述设置恰巧存储在`config.yaml`

**Comment by cubicwork** [comment]
@Ainto codefever-community-lite 镜像是我们早期的一个过渡镜像已经不更新了。storage 和 db 如果已经持久化了以后可以尝试切换到 pgyer/codefever-community 镜像上，pgyer/codefever-community 镜像还随着版本更新在更新。

**Comment by Ainto** [comment]
> @Ainto codefever-community-lite 镜像是我们早期的一个过渡镜像已经不更新了。storage 和 db 如果已经持久化了以后可以尝试切换到 pgyer/codefever-community 镜像上，pgyer/codefever-community 镜像还随着版本更新在更新。

pgyer/codefever-community 镜像出现了：https://github.com/PGYER/codefever/issues/183 问题，我正打算从零开始部署，依然非常感谢

**Comment by cubicwork** [comment]
@Ainto 好的，如果还遇到什么问题直接新开 issue 就行。
