### ISSUE TITLE
配置了秘钥后，clone时候竟然要求输入密码？？？

### ISSUE THREAD

**Issue by libinghope** [PGYER/codefever#202]
<img width="457" alt="1724380978399" src="https://github.com/user-attachments/assets/76fbcdb9-2b96-472b-99c8-fcb53a61cc7d">

不知道该输入什么密码，哪怕输入账号密码也还是不能clone
好像不止我一个人遇到这个问题了，但没有解决办法。
PS:使用docker的方式安装，并且进入容器内.ssh目录中手动增加authorized_keys配置后也不行

**Comment by cubicwork** [comment]
@libinghope  使用 docker 部署时，在使用 ssh 时，如果希望使用默认 ssh 端口进行 git 服务，需要先确定宿主机 22 端口是否被 sshd 等服务占用，如果宿主机 22 端口空闲，可以映射镜像 22 端口到宿主机 22 端口。ssh git 服务需要确认镜像里的 CodeFever 服务是否正常启动，详细维护方式请登录镜像后参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/admin/dashboard.md 来进行维护。
