### ISSUE TITLE
docker-compose 配置的codefever，nginx。  如何在nginx 配置域名

### ISSUE THREAD

**Issue by fengyexin9** [PGYER/codefever#203]
新建docker-compose，配置codefever  8802:80  22:22.  nginx 开启了80 和443端口。
如何在nginx 里面配置codefever的域名，便于 使用域名进行访问，pull 和push

**Comment by fengyexin9** [comment]
不仅需要配置域名，还需要配置ssl，让访问，pull和push 都使用ssl进行操作，需要怎么配置nginx呢？

**Comment by cubicwork** [comment]
1 首先不推荐使用 docker-compose 来运行服务，docker 镜像使用方法参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/install_via_docker.md 来完成。
2. nginx 配置web 服务，需要在宿主机安装 nginx， 然后在宿主机 nginx 配置一个新的 server 段，配置好 ssl 监听 80 和 443 端口后，使用 proxy_pass 系列指令将服务重定向到 docker 绑定的宿主机端口上即可。
