### ISSUE TITLE
源码编译安装方法出现错误

### ISSUE THREAD

**Issue by foundnom** [PGYER/codefever#204]
在第9步“下载源码并安装”的“编译 HTTP 网关服务”中
```
cd /data/www/codefever-community/http-gateway
export GO111MODULE=off
export GOPROXY=https://mirrors.aliyun.com/goproxy
go get gopkg.in/yaml.v2
go build main.go
```
执行到`go get gopkg.in/yaml.v2`时
提示
```
go: modules disabled by GO111MODULE=off; see 'go help modules'
```
我使用的go版本是1.23.3

**Comment by cubicwork** [comment]
@foundnom 您好，你尝试将 `export GO111MODULE=off` 改成 `export GO111MODULE=on` 试一下, 这个 `export GO111MODULE=off` 的设置是我们验证 OK 的设置，如果报错了就去掉再试下，这个 main.go 只要编译完成即可，常量设置对编译出的二进制文件没有影响。

**Comment by foundnom** [comment]
> @foundnom 您好，你尝试将 `export GO111MODULE=off` 改成 `export GO111MODULE=on` 试一下, 这个 `export GO111MODULE=off` 的设置是我们验证 OK 的设置，如果报错了就去掉再试下，这个 main.go 只要编译完成即可，常量设置对编译出的二进制文件没有影响。

我测试了一下在开启了go module（即`export GO111MODULE=on`）之后部署的方式是有所改变
```
go mod init <name>
go mod tidy
go build main.go
```

ps另外开启了go module之后几个main.go中不可以再使用相对路径了
pps我最终使用了go1.16.15成功编译并部署，似乎go1.17开始弃用了go get
ppps可以告知“验证OK的设置”中使用的是什么版本的go吗，我在不开启go module的情况下无论如何都不能成功编译

**Comment by cubicwork** [comment]
@foundnom 我们测试环境使用 go 1.18 版本，很感谢您提供的信息。我们会在文档中更新 go 版本相关的说明。
