### ISSUE TITLE
时间显示请求改进

### ISSUE THREAD

**Issue by yc1121** [PGYER/codefever#206]
当我在凌晨0点提交代码时，提交信息上显示的是上午12点，能否改成0点呢，上午12点这个太不合理了。或者能否提供设置修改为24小时显示呢。
![image](https://github.com/user-attachments/assets/1bd56ed5-55dd-4248-841b-101f1b6844b2)

**Comment by cubicwork** [comment]
@yc1121  收到

**Comment by cubicwork** [comment]
@yc1121 我们已经修改了代码, 使用 24 小时计时法来显示相对时间。 很感谢您的建议。

**Comment by yc1121** [comment]
bug！！！
更新后，最近的项目提交时间仍然显示为以前的形式。如图：
![image](https://github.com/user-attachments/assets/2ee34431-9e7a-41c9-8ef8-4a91d4a81dc7)
其他时间距离较远的项目时间显示正确。请求定位更新修复此bug
