### ISSUE TITLE
最近一周时间显示bug

### ISSUE THREAD

**Issue by yc1121** [PGYER/codefever#212]
继[#206](https://github.com/PGYER/codefever/issues/206)修改显示时间为24小时制后，发现最近一周提交的时间显示仍然旧形式显示，时间较久远的时间显示正常。如图
![image](https://github.com/user-attachments/assets/667d9206-a6ef-46e7-8596-c5efdc0ba7a3)
请求将所有时间均显示为24小时制

**Comment by cubicwork** [comment]
@yc1121  您好，我们并没有在最新版本发现类似截图中的问题，请您确认：
1. 您已经完整的更新了 Codefever
如果上述问题已经确定，请将故障页面的 uri 回复给我们。我们好做进一步的检查。

**Comment by yc1121** [comment]
刚刚又更新了一遍，截图中的问题已经消失了。谢谢
