### ISSUE TITLE
仓库标识串是否不支持下划线_

### ISSUE THREAD

**Issue by shuyudao** [PGYER/codefever#22]
在push时，返回 xxx：is this a git repository?

去掉下划线_则可以正常PUSH

**Comment by cubicwork** [comment]
@shuyudao 仓库 URL 在设计时是支持下划线的。我们会详细检查你提到的问题。并在下一个版本修复。

**Comment by cubicwork** [comment]
hi. 你描述的缺陷已经修复合并，你可以参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/update.md 来更新 CodeFever
