### ISSUE TITLE
查看仓库提交信息出错白屏

### ISSUE THREAD

**Issue by shuyudao** [PGYER/codefever#23]
**出错路由：/XXX/xxx/commits**

错误信息：

```
TypeError: Cannot read properties of null (reading 'substr')
    at a.value (main.f834e978.js:formatted:15217:62)
    at Go (1.18365ff4.chunk.js:formatted:31258:82)
    at $o (1.18365ff4.chunk.js:formatted:31248:16)
    at Yc (1.18365ff4.chunk.js:formatted:33852:13)
    at Al (1.18365ff4.chunk.js:formatted:32985:17)
    at _l (1.18365ff4.chunk.js:formatted:32978:13)
    at Tl (1.18365ff4.chunk.js:formatted:32962:17)
    at yl (1.18365ff4.chunk.js:formatted:32726:17)
    at 1.18365ff4.chunk.js:formatted:29658:33
    at t.unstable_runWithPriority (1.18365ff4.chunk.js:formatted:34517:20)
```

**不是所有的仓库都会出错，就这个出错，疑似对提交信息的字符串处理出现问题，下方是我这边repository/commitList返回的提交信息数据**

https://gist.github.com/shuyudao/c30eeb085817b475ea20d432cf4302b7

**Comment by cubicwork** [comment]
@shuyudao 您好 问题已经收到，你的判断应该没有错误，我们会在假期结束后修复此问题。

**Comment by cubicwork** [comment]
hi. 你描述的缺陷已经修复合并，你可以参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/update.md 来更新 CodeFever

**Comment by shuyudao** [comment]
在我更新完成之后 经过检查发现还是报同样的错误。
 
确认更新脚本正常运行完成且返回 CodeFever Comminuty Upgrated；确认清除了浏览器缓存；

**Comment by cubicwork** [comment]
@shuyudao 请在项目根目录的文件列表打印出来截图上传一下。如果信息机密请发送邮件到 carneywu@pgyer.com 并表明 issue 编号即可。

打印文件列表方法
unix-like OS or Windows Power Shell
``` shell
cd <project folder>
ls -al .
```
windows cmd
``` shell
cd <project folder>
dir
```

**Comment by shuyudao** [comment]
没有变化

![image](https://user-images.githubusercontent.com/31978102/159096382-a20bc78e-1fce-4e7f-b26d-c2b6d6c84d65.png)

**Comment by cubicwork** [comment]
@shuyudao 不好意思，可能是我没表达清楚，我需要的是 你出错的那个项目的本地仓库的根目录的文件列表截图，如果信息机密请发送到 carneywu@pgyer.com 并同时在邮件正文中写上 issue number。

**Comment by cubicwork** [comment]
@shuyudao 如果不是项目首页白屏，只是 commit 列表白屏，报错和此 issue 信息最早描述的一样，请直接回复此 issue 确认一下。我们重新排查问题。

**Comment by shuyudao** [comment]
> @shuyudao 如果不是项目首页白屏，只是 commit 列表白屏，报错和此 issue 信息最早描述的一样，请直接回复此 issue 确认一下。我们重新排查问题。

只是 commit 列表白屏，报错和此 issue 信息最早描述的一样

**Comment by cubicwork** [comment]
@shuyudao 好的，您先不要着急，我们安排人员排查问题，此 issue 打开。修复结果会在此 issue 中跟进。

**Comment by cubicwork** [comment]
@shuyudao 您好，我们需要以下内容来帮助我们排查问题：
在出现问题的仓库的本地仓库副本根目录中运行一下命令并将回复生成的文件到本 issue 中, 我们想了解具体是哪一类特殊字符引起的此问题。

``` shell
git log -n50 > commit_log.txt
```

非常感谢

**Comment by shuyudao** [comment]
👉 https://gist.github.com/shuyudao/f9ba19d1cbcf1ee18c37ee1fcf7bb5b0

**Comment by cubicwork** [comment]
@shuyudao hi, 我们针对你遇到的问题已经修复，请按照 Readme 中 如何更新 一节更新你的 CodeFever 即可。
