### ISSUE TITLE
是否支持webhook

### ISSUE THREAD

**Issue by hnh0000** [PGYER/codefever#24]
未找到支持仓库webhook的地方

**Comment by cubicwork** [comment]
@hnh0000 webhook 已经在计划中了，预计下一个词要更新就能支持。

**Comment by hnh0000** [comment]
👍
如果能新增自定义使用第三方系统oauth2来登录就更好了。

**Comment by cubicwork** [comment]
@hnh0000 感谢意见。 OAuth 目前还没有在开源版本的计划中，目前云服务版本计划中有 OAuth。

**Comment by cubicwork** [comment]
@hnh0000  hi, 您好, 我在在最近的更新中已经添加了 Webhook 特性。 你可以参照 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/index.md 更新或重新安装 CodeFever 来体验。如果遇到期望外问题可以重新提 issue。
