### ISSUE TITLE
默认的两个用户，组和仓库是否可以删除？

### ISSUE THREAD

**Issue by huabin** [PGYER/codefever#30]
感谢你们提供一个不错的选择。

我想请问下，默认的两个用户 `test` 和 `test2`，以及仓库组 `codefever`，仓库 `codefever` 是否可以删除呢？

**Comment by cubicwork** [comment]
@huabin  默认的 test 用户以及 codefever/codefever 仓库是单执行元测试的必要选项 （这两个用户只是存在于用户体系中并且被禁止登录）。如果你没有自行魔改 CodeFever 的需求，可以移除。 

按照以下步骤可以移除测试数据:
- 进入管理后台
- 到 仓库组 管理 选择成员管理 将自己设置为 仓库组 的 所有者
- 到 CodeFever 首页后刷新页面进入需要删除 仓库 的设置页面删除仓库
- 用上一步相似的办法删除 仓库组
- 登录 shell 进入到数据库，在 cc_users 表中直接删除不想要的用户即可。

我们后期会考虑提供一个删除测试数据的脚本以便操作

**Comment by huabin** [comment]
@cubicwork 多谢

**Comment by cubicwork** [comment]
@huabin 也运行以下 SQL 直接删除所有测试数据。

``` sql
use codefever_community;
DELETE FROM cc_users WHERE u_key = '26c20714af8bc20aa85be657a5170e71';
DELETE FROM cc_users WHERE u_key = 'f4a9c54adef17599d4f709a1167f0fcd';
DELETE FROM cc_ssh_keys WHERE u_key = 'f4a9c54adef17599d4f709a1167f0fcd';
DELETE FROM cc_repositories WHERE r_key = '2f941aef39bc8a048da55dd28c678655';
DELETE FROM cc_groups WHERE g_key = 'e6508c1a66e86f697c96bdffb30c1ae3';
```
