### ISSUE TITLE
env.yaml配置咨询

### ISSUE THREAD

**Issue by yudongjian** [PGYER/codefever#38]
使用零基础安装方式进行安装后，env.yaml配置中的session中的key，以及gateway中的token如何配置；谢谢！

**Comment by cubicwork** [comment]
@yudongjian 这两项属于安全设置，如果你在公网上提供服务，我们强烈您修改这两个配置。

- `session key` 是用于加密 `cookie` 的 key。 你可以修改成任意符合 `/[0-9a-z]{1,32}/i` 模式的字符串。
- `gateway token` 用于内部 GIT SSH/HTTP 网关与主服务交互时的 token。你可以修改成任意符合 `/[0-9a-z]{1,32}/i` 模式的字符串。
