### ISSUE TITLE
2FA Have an error

### ISSUE THREAD

**Issue by v8oo00** [PGYER/codefever#39]
There was an error when I used bind MFA and I couldn't bind
<img width="1575" alt="123" src="https://user-images.githubusercontent.com/38418014/154230484-135aad64-f1fb-454d-a8d4-363827a97755.png">

**Comment by cubicwork** [comment]
@v8oo00  您好，第一个输入框用于填写 第一组 2FA 验证码，第二个输入框用于填写第二组 2FA 验证码，填写完第一组验证码之后需要等待 30s 后等 2FA App 验证码跳到下组时再填写。

hi, you should input different two 2FA Code into 2 input box.  Open your 2FA App and Scan QR Code, input the 2FA into the 1st input box, then wait the 2FA  App code change  (about 30s), and input new 2FA Code input the 2nd input box, then click save btn.

**Comment by v8oo00** [comment]
> 

All right. Thank you.
