### ISSUE TITLE
配置好ssh key之后，git clone 仍然需要密码

### ISSUE THREAD

**Issue by wasdty** [PGYER/codefever#41]
配置好ssh key之后，git clone 仍然需要密码

**Comment by shishirui** [comment]
如果配置正确，肯定是不需要的。可以在网上搜索下配置方法，对照着仔细检查一下。

**Comment by wasdty** [comment]
我配置的GitHub，git clone不需要密码，请问docker服务器上还需要什么配置吗

**Comment by dcncy** [comment]
> @wasdty 引起这个情况的原因有很多，请你按照如下情况检查：
> 
> * 启动 docker 时是否包含了 --privileged=true 选项
> * 到管理员后台检查 codefever 服务是否正在运行
> * 你的宿主机是否已经把 22 端口（SSH 默认端口）空余出来并将在启动 docker 镜像时使用了 -p 22:22 选项
> 
> 如果以上情况都排除可问题依然存在，请回复此 issue。

大佬，我使用的是docker部署，但是我将22端口映射为宿主机的其他端口了，这种情况，ssh连接不上应该怎么解决？
