### ISSUE TITLE
零基础安装方式yaml安装失败

### ISSUE THREAD

**Issue by jiantaozi** [PGYER/codefever#43]
你好，虽然官网建议使用root用户，但是因环境问题只能使用非root用户；
当执行到php的扩张yaml安装时，configure提示Please install libyaml；虽然我已经安装了yaml的依赖libyaml 0.2.5，并且将lib路径放入环境变量LD_LIBRARY_PATH，但是还是提示需要安装libyaml；

希望您能帮忙解答我的疑问，万分感谢

**Comment by cubicwork** [comment]
@jiantaozi hi, 您好，安装 yaml 扩展由于 php 扩展的 C 代码需要 link，因此需要安装 yaml 的 header 文件，你需要确认你的系统已经安装 libyaml-devel 库。
您需要想办法获得 root 权限，使用 sudo su 切换到 root 用户也可以。因为 CodeFever 的 chkconfig 服务、 init 脚本 和 SSH Key 服务都需要 root 权限才能正常运行。 安装过程中还需要创建 git 用户，因此 root 用户权限是必要的。
