### ISSUE TITLE
docker部署的数据转储

### ISSUE THREAD

**Issue by Drswith** [PGYER/codefever#47]
如题 docker部署时，如何访问到容器的数据库？
默认条件下 docker run命令增加　-p 暴露容器3306端口，使用navicat连接时提示“ Host ‘gatway ’ is not allow to connect to this MariaDB server”

![QQ截图20220307173034](https://user-images.githubusercontent.com/49299002/157004615-3c648057-1039-4e51-82c2-a0fc4dc269ea.png)

**Comment by cubicwork** [comment]
@Drswith 您好，1. 在使用 docker 暴露端口前，您需要确定您的宿主机的 3306 端口是否已经被占用。如果已经被常用，需要映射到其它端口。2. docker 镜像中的 mariadb 被设置设置成仅止除了 localhost 主机之外禁止访问，你需要登录 docker 后自行调整权限。或者使用 CREATE USER 命令为自己创建一个新的管理用户（推荐）。

具体操作如下:
1. 使用 docker exec 启动 docker 镜像的 shell 
2. 使用 `mysql -uroot -p123456` 来登录数据库
3. 使用 `create user 'admin'@'%' identified by '123456'; ` 创建一个用户名是 admin 密码是 123456 并允许任何 host 访问数据库的用户。
4. 使用 `grant all privileges on codefever_community.* to 'admin'@'%';` 为用户授权数据库权限
5. 使用 `flush privileges;` 来更新权限设置。
6. 在宿主机上使用 admin / 123456 来访问数据库
