### ISSUE TITLE
无法新增SSH Key

### ISSUE THREAD

**Issue by Wind-Night** [PGYER/codefever#48]
新增SSH Key貌似存在问题，我将SSH Key直接粘贴上去，但是始终显示**请输入SSH Key**，还有用户管理里面也没有找到如何删除用户。

**Comment by cubicwork** [comment]
@Wind-Night 您好，你出现的情况如果是在输入框下方提示的，这说明您的 SSH Key 输入框没有内容。请将 SSH Public Key 的内容粘贴到大的输入框中，如果你的输入正确，名称输入框会被自动填写为 SSH Public Key 的名称。如果以上回答没有解决问题，请继续回复此 issue

**Comment by Wind-Night** [comment]
报告已收到

**Comment by Wind-Night** [comment]
我已将SSH Public Key输入到框内，但是点击提交时依旧不可以。![image](https://user-images.githubusercontent.com/79204013/157370296-da379b87-5193-4f94-81b0-d18d5f131fb8.png)

**Comment by cubicwork** [comment]
@Wind-Night 您好，我们这边已经按照你的描述做了验证，并没有复现出你所描述的问题。顺利复现该问题需要获得您的帮助。

请按完成下操作帮助我们定位问题：

### 1. 更换浏览器再次加入同样的 SSH Key
如果问题解决： 回复我们你出现该问题的浏览器名称和版本号
如果问题未解决：进行下一步骤

### 2. 尝试在我们的线上 Demo (http://114.132.251.156/settings/sshkey) 上添加你的 SSH Key
如果问题解决： 尝试更新一下 CodeFever 看看问题是否得到解决
如果问题未解决：回复我们你的 SSH Key 我们观察啥是否是 格式或者是特殊字符的问题

**Comment by Rabbit0w0** [comment]
您好, 请确认 SSH Key 行尾不存在多余的换行符

**Comment by cubicwork** [comment]
> 您好, 请确认 SSH Key 行尾不存在多余的换行符 @cubicwork 出来挨打

竟然被你发现了 bug 的精髓所在，我要把这个问题标记为 bug

**Comment by Wind-Night** [comment]
@Rabbit0w0 感谢你的帮助，直接复制粘贴有可能会在最后多一个换行，这导致了无法新增ssh key。
