### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by xin6841414** [PGYER/codefever#49]
问题一：私有化docker部署之后，页面无法打开问题
部署完成 打开ip地址，输入账号密码后，页面一直在转圈（屏幕中央显示codefever），存在于ubuntu18.04桌面版（火狐浏览器），安卓手机（uc浏览器），window10系统正常。
问题二：新建仓库组之后，在设置-》高级页面修改 更新仓库组URL 修改为少于5位字符的地址触发一系列页面故障（此处未限定5位字符，左侧导航白屏，设置无法打开，新建仓库空白等等
希望修复！

**Comment by cubicwork** [comment]
@xin6841414 感谢提出问题。 我们会对你提出的问题进行验证和修复，相关进度会在此 issue 中跟进

**Comment by cubicwork** [comment]
您好 您的问题 我们修复了 问题2， 关于问题1，我们希望你使用较新的浏览器来访问 CodeFever。 关于如何更新请参照 readme 中关于更新的章节
