### ISSUE TITLE
无法发送邮件

### ISSUE THREAD

**Issue by Rabbit0w0** [PGYER/codefever#51]
![image](https://user-images.githubusercontent.com/21006278/157449672-3d8f018f-7c23-49fd-9324-18c71674bc06.png)
![image](https://user-images.githubusercontent.com/21006278/157449786-d11f216b-adfa-433d-b922-7c37ccf13881.png)
![image](https://user-images.githubusercontent.com/21006278/157449911-4e3c5843-7439-421f-ba89-4122debbd781.png)
---
如题, 无法发送邮件, SMTP设置等已附图

**Comment by Rabbit0w0** [comment]
![image](https://user-images.githubusercontent.com/21006278/157676897-95e6ae62-0594-4826-a8ec-7f6b49790213.png)
![image](https://user-images.githubusercontent.com/21006278/157676921-77170233-461a-413c-9458-7201ef03a851.png)
![image](https://user-images.githubusercontent.com/21006278/157677039-4f37877a-c4fe-4627-90ee-a5c8200f7a27.png)
---
然而事实上好像雀实发不出去

**Comment by cubicwork** [comment]
@Rabbit0w0 您好，您的安装方式是 docker 方式 还是 从零开始安装 方式。 这可能不是你的问题，我们的 docker 镜像没有预安装 mailx 服务。此问题会在下次更新时修复。

如果是 docker 方式：
1. 登录容器 shell，运行 `yum install -y mailx` 安装 mailx，然后再检查邮件是否能够收到
2. 如果仍然收到不到邮件，请回复 收件地址 我们确认下邮件是否被收件服务器拦截

如果使用 从零开始安装 方式：
1. 运行 `yum install -y mailx` 安装 mailx，然后再检查邮件是否能够收到
2. 如果仍然收到不到邮件，请回复 收件地址 我们确认下邮件是否被收件服务器拦截

**Comment by Rabbit0w0** [comment]
![image](https://user-images.githubusercontent.com/21006278/157807965-f2304c16-9018-4b82-bd96-eb29ca310c31.png)
---
仍无法收到邮件, 已尝试Gmail QQ邮箱 Outlook

**Comment by cubicwork** [comment]
@Rabbit0w0  hi，你好，我们会对代码做更进一步的检查。目前已经确认，这大概率不是设置上问题。有进一步消息我们会在此 issue 内跟进。

**Comment by cubicwork** [comment]
@Rabbit0w0 问题已经修复，参照 Readme 文档中中的 `如何更新`  章节即可更新

**Comment by Rabbit0w0** [comment]
![image](https://user-images.githubusercontent.com/21006278/157847164-9d0a5c09-d854-4f32-b412-7cfd0256ba19.png)
![image](https://user-images.githubusercontent.com/21006278/157847203-01df3e48-2d91-4bdd-b7ed-4b82f738c819.png)
---
顺便提交一个Bug, 重发单个邮箱的验证码时其他待验证邮箱也会显示已重发

**Comment by cubicwork** [comment]
@Rabbit0w0 还没有解决么 我先把 issue 打开 周一上班后我们再看看代码层面上有没有问题

**Comment by cubicwork** [comment]
@Rabbit0w0  问题已经解决了，按照 Readme 中的链接的更新步骤去更新。https://github.com/PGYER/codefever/blob/master/doc/zh-cn/admin/settings.md 文档会指导如何设置解析。
邮件从触发到接收到需要大概 2min 时间
如果还有什么问题请继续回复此 issue
