### ISSUE TITLE
【咨询】开源的comminuity版本是否支持多活?和公有云版本相比有哪些差异点呢？

### ISSUE THREAD

**Issue by HMcomcrazy** [PGYER/codefever#52]
请教下，开源的comminuity版本是否支持多活模式（可以避免单机部署时的故障）?和公有云版本相比有哪些差异点呢？

**Comment by cubicwork** [comment]
@HMcomcrazy
Community 版本是专门经过单机优化的版本，适合单机部署，不支持多活。

和公有云版本相比：
1. Community 版本主要逻辑代码以及功能特性和公有云代码一致，两个版本基本同步更新。
2. Community 版本在公有云版本基础上做了单机部署优化。因此不支持多活和分布式部署。
3. Community 版本开放所有源代码以供审查、评估和学习交流。使用时更安心并且可以自己定制。
4. 公有云版本是集群版本，并与蒲公英用户中心和工单系统相连接，账号可以享受蒲公英全部服务。(包括不限于：任务追踪、知识库、前端性能监控、内测分发、工单和技术支持 及 企业管家等服务)
