### ISSUE TITLE
仓库界面无法显示

### ISSUE THREAD

**Issue by TobiasHu2021** [PGYER/codefever#53]
docker部署的codefever，使用一段时间后，仓库的界面无法显示，前端控制台报错如下：
![1bd2b4cb5cb002ac961689239f81a90](https://user-images.githubusercontent.com/12579229/157617682-f133cf2c-8ec1-4484-89f4-a7f6570b89ef.png)

**Comment by cubicwork** [comment]
@TobiasHu2021 您好，需要你补充更详细的信息：

1. 出错页面的 URL

**Comment by TobiasHu2021** [comment]
> 
URL：http://127.0.0.1:8080/flysec/knowledge_base

**Comment by cubicwork** [comment]
@TobiasHu2021 您的反馈已收到 项目首页 显示白屏 我们看下具体原因  bug 修复情况会在此 issue 中跟进

**Comment by TobiasHu2021** [comment]
> @TobiasHu2021 您的反馈已收到 项目首页 显示白屏 我们看下具体原因 bug 修复情况会在此 issue 中跟进

你好，具体错误，我已经排查出来了。

![1646966552(1)](https://user-images.githubusercontent.com/12579229/157792165-7d6558e9-ec27-448b-9879-723dcc262d38.png)

导致前端不能够正常是由于我目录结构中存在着有空格隔开的文件夹命名，导致后台在计算sha的时候值是空。具体信息如下：

![1646966879(1)](https://user-images.githubusercontent.com/12579229/157792663-90b6dd42-6fb1-4b8c-9fcc-3fef26be0c19.png)

我看了我Git的提交记录，我这边是可以正常计算sha值的，这个应该是和后台有关，而不是简单的对前端react修复？

**Comment by cubicwork** [comment]
是的 我们只能从你前端提供的信息来判断故障原因 更多的信息才能获得更详细的故障原因 很感谢你提供的信息 这些信息很有用

**Comment by cubicwork** [comment]
@TobiasHu2021 问题已经修复，参照 Readme 文档中中的 `如何更新`  章节即可更新

**Comment by cubicwork** [comment]
变更已回滚 重新打开

**Comment by cubicwork** [comment]
@TobiasHu2021  问题已解决，按照 Readme 中的链接的更新步骤去更新即可。
