### ISSUE TITLE
[反馈] 删除侧边栏多余的滚动条以及正确计算存储库大小

### ISSUE THREAD

**Issue by Rabbit0w0** [PGYER/codefever#56]
![image](https://user-images.githubusercontent.com/21006278/157835006-53fc318f-039b-43f7-b705-0b1a5bdf7400.png)
如图

**Comment by cubicwork** [comment]
@Rabbit0w0 hi, 您好，感谢反馈。问题会在下次更新是修复。修复进度可以关注此 issue

**Comment by cubicwork** [comment]
@Rabbit0w0  问题经解决，按照 Readme 中的链接的更新步骤去更新即可。
