### ISSUE TITLE
[MODERATE] 无法显示子模块

### ISSUE THREAD

**Issue by Rabbit0w0** [PGYER/codefever#60]
如题, 无法正常显示Git子模块

值得一提的是, #51 的问题也还没有解决

**Comment by cubicwork** [comment]
@Rabbit0w0 hi 感谢提出问题 我们会考虑增加此特性

**Comment by cubicwork** [comment]
@Rabbit0w0 您好，您请求的特性我们已经添加并合并，更新后即可体验。 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/update.md
