### ISSUE TITLE
bug. 修改主机 url 后仓库组和仓库的地方并不会随之更新。

### ISSUE THREAD

**Issue by wdssmq** [PGYER/codefever#67]

**Comment by wdssmq** [comment]
好像退出登录重进才会变。。

**Comment by cubicwork** [comment]
@wdssmq 需要刷新页面才能改变。 这块我们需要再优化一下，我先标记成 bug

**Comment by cubicwork** [comment]
@wdssmq hi, 我们针对你遇到的问题已经修复，请按照 Readme 中 如何更新 一节更新你的 CodeFever 即可。
