### ISSUE TITLE
默认账号邮箱及密码修改

### ISSUE THREAD

**Issue by wdssmq** [PGYER/codefever#68]
个人信息（邮箱）和密码在修改后要各自点一次保存；

忘记保存时切换页面并不会提示；

修改后当前登录也不会失效；

所以说。。Docker 创建时为什么不用 -e 参数让用户自己设置邮箱和密码呢。。

**Comment by cubicwork** [comment]
@wdssmq 您好，docker 版本在制作的时候准备时间较短，因此 全局变量的方式并没有被考虑。其余行为均与 cloud 版本保持一致，因此没有多专门的调整。
