### ISSUE TITLE
实时

### ISSUE THREAD

**Issue by yudongjian** [PGYER/codefever#69]
谢谢

**Comment by cubicwork** [comment]
@yudongjian 您好，能否描述的更详细一些，如果是页面显示异常请粘贴 url 我们判断是哪个页面出现的问题。

**Comment by yudongjian** [comment]
> @yudongjian 您好，能否描述的更详细一些，如果是页面显示异常请粘贴 url 我们判断是哪个页面出现的问题。

您好，谢谢您了，问题已经解决了，问题是创建数据库时，缺少了一些表格，问题已经解决了，谢谢
