### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'slice')

### ISSUE THREAD

**Issue by Aiden-Coding** [PGYER/codefever#70]
点击查看项目出现空
<img width="1325" alt="Snipaste_2022-03-19_03-28-41" src="https://user-images.githubusercontent.com/57240668/159071395-d8c6edf3-8d76-4a20-8553-c82f0140ea54.png">
白

**Comment by cubicwork** [comment]
@Aiden-Coding hi，您好，请按 readme 文档中的 如何更新 章节更新您的 codefever。如果问题依旧，请在将项根目录的文件列表打印出来截图上传一下。

打印文件列表方法
unix-like OS or Windows Power Shell
``` shell
cd <project folder>
ls -al .
```
windows cmd
``` shell
cd <project folder>
dir
```

**Comment by Aiden-Coding** [comment]
@cubicwork 更新版本，没有问题了
