### ISSUE TITLE
仓库创建失败

### ISSUE THREAD

**Issue by jiantaozi** [PGYER/codefever#72]
新建完仓库组后，新建仓库时一直提示创建仓库失败，请稍后重试
console错误提示为：http://192.168.56.107:1080/api/repository/create? 400 (Bad Request)

![image](https://user-images.githubusercontent.com/57781812/160034409-e6483afb-ba93-4a0e-b108-3873f6ef2d6a.png)

**Comment by cubicwork** [comment]
@jiantaozi 您好，我们需要了解更多信息：

1. 您的安装方式  `docker` 还是 `从零开始安装`
2. 在按照文档安装后是否做过某些设置上更改或者备份恢复行为
3. 安装后就不能创建仓库 还是 曾经可以创建仓库

**Comment by jiantaozi** [comment]
1、我使用的是零基础安装
2、不过因为80端口不能使用，我修改为了1080端口不知道是不这个问题的缘故，而且env.yaml中gateway是否需要对应更新指定端口，config.yaml中的host是否也需要指定端口
3、一直不能创建仓库，只能创建仓库组
4、codefever-service-template启动作用是撒，不启动好像也不影响创建仓库组，

**Comment by cubicwork** [comment]
@jiantaozi 您好
1. 80 端口不能使用，需要修改 nginx 端口，在 `/usr/local/nginx/conf/nginx.conf` 文件中修改即可。`env.yaml` 文件中的 `gateway.hooks`, `gateway.authHTTP`, `gateway.authSSH`  都需要修改成相应的端口, 不过这些设置应该不会导致你不能创建项目。
2. codefever-service-template 这个脚本只是个模版，实际的服务我们已经在你运行 install.sh 的时候注册到 init 脚本目录内。

接下来可能有用的解决方案
1. 使用管理员账户登录 codefever 到管理员->概览面板看一下所有服务是不是已经都启动了。 (doc/zh-cn/admin/dashboard.md)
2. 使用 cat /etc/passwd 看下  www 和 git 是否都存在，查看 /data/www/codefever-community/git-storage 是否所有者为 root 或 git 并且权限是 0777

如果有不符合项，请按照上述检查项进行修改，如果没有不符合项，可以尝试 更新 codefever 到最新版本再看问题是否还存在。

**Comment by jiantaozi** [comment]
你好，根据你说的我做了对应修改，但是没有得到预想的结果，
nginx配置了两个service一样的端口，请问是否都要修改，proxy_pass是否也需要加上端口
请问哪里有记录后台服务端日志，想看下具体是哪里出现了错误

**Comment by cubicwork** [comment]
@jiantaozi 您好
1. 名称为 localhost-dev 的服务是开发用的服务，不需要修改
2.` /data/www/codefever-community/application/logs `目录记录服务级别的 log，你需要将此目录 chown 为 git 用户 或 chmod 为 0777 即可查看 log。
3. 你确认下 `ll /usr/local/bin/git` 是否存在，如果你不存在需要 `ln -s /usr/local/git/bin/git /usr/local/bin/` 一下
