### ISSUE TITLE
容器启动时报Failed to start LSB: Bring up/down networking.有影响吗

### ISSUE THREAD

**Issue by skyatgit** [PGYER/codefever#75]
容器启动时出现
Failed to start LSB: Bring up/down networking.
See 'systemctl status network.service' for details.
![image](https://user-images.githubusercontent.com/42607334/160317650-7171e723-63be-46aa-9e7f-6e5f90388484.png)
这个错误会有什么影响吗
如何解决

**Comment by cubicwork** [comment]
@skyatgit  对于这个错误，只要容器启动后 网络能够访问 就可以忽略。 具体需要登录 docker 容器看看 network 服务的日志才能清楚具体是因为什么原因。 一般情况下 只要按照 doc 中的参数设置 不会有这样的错误。

**Comment by skyatgit** [comment]
我进容器看了一下发现是mirrors.tencentyun.com连不上，他们的源好像改成了mirrors.cloud.tencent.com

**Comment by cubicwork** [comment]
@skyatgit 您的问题我记录一下，我们会在适当的时候修改 yum 源的设置。目前我们 build 镜像还没有受到这个域名的影响。大概率是因为我们打镜像的操作是在腾云上完成的，内部网访问这个地址是 ok 的原因。 如果这个对你影响很大的话，你可以将 yum 源切换到 速度比较快的公共镜像上

**Comment by skyatgit** [comment]
好的，不过更新源后依旧没有解决此报错，目前没有发现有任何影响，后续发现了问题或解决方法我会在此处更新
