### ISSUE TITLE
SMTP相关问题

### ISSUE THREAD

**Issue by skyatgit** [PGYER/codefever#76]
请问这个SMTP功能，这个是向宿主机的25端口发信吗
如果宿主机没有SMTP功能想要使用第三方邮箱例如qq邮箱和网易邮箱，该如何配置呢

**Comment by cubicwork** [comment]
@skyatgit 
1. SMTP 只要按照 `从头开始安装` 和 `docker 镜像安装` 中都是带 sendmail 服务的。 发信不是向宿主机发信，而是向收件邮箱的邮件服务器直接投递。按照 `doc/zh-cn/admin/settings.md` 中的描述去设置 SMTP 参数和域名解析，即可直接向目标邮箱投递电子邮件。 阅读 `doc/zh-cn/admin/dashboard.md` 文档可以帮你了解你所有服务是否运行正常。
2. 只要按照安装文档安装，宿主机不需要额外的 SMTP 服务器

**Comment by weixuan00** [comment]
请问能否添加第三方邮箱发信的功能呢？

**Comment by cubicwork** [comment]
@weixuan00 您好，目前不支持第三方邮箱，您可以订阅 `webhook` 来自己完成第三方邮件的发送。或者修改 `application/libraries/service/MessageService/Email/EmailSender.php` 文件添加新的邮件 `handler` 来支持第三方邮件发送。
