### ISSUE TITLE
git push认证失败

### ISSUE THREAD

**Issue by jiantaozi** [PGYER/codefever#77]
使用零基础安装时，push认证失败，操作及错误如下图：
![屏幕截图 2022-03-28 163237](https://user-images.githubusercontent.com/57781812/160358488-d24cd273-5cbb-4b0f-9c01-341a88e8c7d3.png)

通过管理用户查看管理台中各类服务状态均为绿色的Running状态，能否给点建议可能是哪里出现了错误，上诉的用户名和密码可以确定没有输入错误，为默认的管理员账户和密码root@codefever.cn

**Comment by cubicwork** [comment]
@jiantaozi 
1. 您是 docker 安装还是从 零开始安装
2. 如果是 `从零开始安装` 如果修改了 web 端口需要同步修改 env.yaml 文件中 gateway 相关参数
3. 如果是 `docker 安装`，**不需要**修改 env.yaml 文件

**Comment by jiantaozi** [comment]
我使用的是零基础安装，gateway的参数已经是追加了端口号的，是否跟token有关系，我设置的token可以是任意的吗？

**Comment by cubicwork** [comment]
@jiantaozi token 只要满足 /[0-9a-f]{32}/ 这个模式即可， 零基础安装 修改端口号后需要修改 nginx 服务的端口号，同时需要修改  env.yaml 文件中 gateway url 相关参数中的端口部分，如果指定了 server name ，需要修改  env.yaml 文件中 gateway  url 相关参数中的 host。 在修改玩以后需要重启 nginx 服务。

**Comment by jiantaozi** [comment]
nginx端口号肯定改了，否则也无法访问，server name使用默认的localhost所以也无需修改，还有可能是其他原因吗

**Comment by cubicwork** [comment]
@jiantaozi 没有了 你尝试一下

# service codefever stop
# service codefever start

重启一下服务。如果还不行，请发邮件到 carneywu@pgyer.com 附上您的微信号，我们帮你检查一下。

**Comment by jiantaozi** [comment]
最后补充下，我发现我用户未开启2FA，请问跟这个是否有关系，这个的作用是什么

**Comment by cubicwork** [comment]
@jiantaozi  2FA 只做登录保护，相当于二次验证。 GIT HTTP 验证不通过和这个没有关系的

**Comment by jiantaozi** [comment]
你好，我已将微信号发你邮箱，请查收

**Comment by jiantaozi** [comment]
你好，我刚查看了logs下面api日志显示如下错误，看下是否能够看出问题：
![image](https://user-images.githubusercontent.com/57781812/160971266-4979cd37-b6d2-4246-99d1-2e8e82266f31.png)

**Comment by cubicwork** [comment]
@jiantaozi 我给你发了一封邮件，你先加一下我，我加不上你。 目前看应该不是设置的问题， authHTTP 能看到 log 说明网络方面是没有问题。返回 403(257) 主要是因为此账号没有此仓库的访问权限的原因。你可以在网页上检查一下此账号是否具有此仓库的权限，并且在仓库成员中的角色可以 push 代码到仓库。 具体参照 `doc/zh-cn/repo/members.md` 来设置角色，至少需要 开发者 / 维护者 / 所有者 角色 才能 push 代码

**Comment by jiantaozi** [comment]
你好，我使用的就是默认管理者，而且这个仓库就是该用户创建的：
仓库设置：
![image](https://user-images.githubusercontent.com/57781812/160986464-2003a30b-a3b8-438f-a84f-f6df62f5e4ed.png)
执行步骤尝试了邮箱和用户名都不行：
![image](https://user-images.githubusercontent.com/57781812/160985897-e58ba441-301c-4af9-8bcc-c7ed16f407e4.png)
日志结果：
![image](https://user-images.githubusercontent.com/57781812/160986327-88a5f878-8f89-4e0d-8da4-ea15f9b5ece8.png)

**Comment by cubicwork** [comment]
@jiantaozi 403 (257) 错误进存在于用户名或密码不正确的情况，用户名应该是您的登录邮箱。您需要确认您的用户名和密码是否输入正确。

我们推测你的账号密码可能已经被修改，你可以尝试重置你账户的密码后再次使用新密码试一下。

如果安装正确，默认密码应该如下图所示：

<img width="534" alt="image" src="https://user-images.githubusercontent.com/9900088/160988848-0369d3b8-19ae-42fc-a962-655044424a99.png">

**Comment by jiantaozi** [comment]
你好，我的密码是跟后台日志显示的用户名和密码一致的，我采纳了你的意见重新重置为一样的，还是不行
日志如下：



页面显示的用户名和密码如下：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PGYER/codefever"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PGYER/codefever] git push认证失败 (Issue #77)





 
@jiantaozi 403 (257) 错误进存在于用户名或密码不正确的情况，用户名应该是您的登录邮箱。您需要确认您的用户名和密码是否输入正确。
 
我们推测你的账号密码可能已经被修改，你可以尝试重置你账户的密码后再次使用新密码试一下。
 
如果安装正确，默认密码应该如下图所示：

**Comment by cubicwork** [comment]
@jiantaozi 你看一下我给你发的邮件，我给你发了一个二维码，你用微信添加一下，我们私聊解决一下。

**Comment by cubicwork** [comment]
标记为bug：env.yaml 文件 gateway.token 的值必须包含字母或其他特殊符号，不能是纯数字。否则会产生类型不一致的问题。
