### ISSUE TITLE
初始的管理员账号在加入其他人的项目和项目组时无法被移除

### ISSUE THREAD

**Issue by skyatgit** [PGYER/codefever#78]
如题，但移除时会返回移除成功的提示，但实际没有被移除

**Comment by skyatgit** [comment]
![image](https://user-images.githubusercontent.com/42607334/160393135-d6081abf-365a-455b-95ee-f4970f1ee358.png)
![image](https://user-images.githubusercontent.com/42607334/160393202-6642759e-6ae6-4f79-a835-8cae52d89674.png)

**Comment by skyatgit** [comment]
![image](https://user-images.githubusercontent.com/42607334/160397169-7a21684e-2f21-4baf-9db0-75e802ba2ebd.png)
![image](https://user-images.githubusercontent.com/42607334/160397230-9570bd0a-af9f-4fd6-bb0d-d2aa11ee2e79.png)
这个地方也会出现类似的问题

**Comment by cubicwork** [comment]
@skyatgit 
1. 在仓库管理中无法移除仓库组成员，仓库组成员默认拥有所有组内仓库对应权限，除非再仓库里重新指定。
2. 在仓库内移除成员，成员不再拥有仓库访问权限，但是成员列表中依然会出现该成员信息，并且标记成已删除。（因为该成员可能对仓库有 commit 因此需要保留该成员信息。但是成员标记上已删除选项后已经失去该仓库访问权限）

具体形况我们会安排开发人员进行检查，有结果我会回复此 issue

**Comment by cubicwork** [comment]
@skyatgit 您好，在仓库中不能将仓库组成员移除。如果要移除仓库组成员，应该在仓库组的成员列表内移除仓库组成员。 我们会在后期版本中在仓库成员列表中去掉移除仓库组成员的选项。

**Comment by cubicwork** [comment]
已修复  6eca787a691426f201836b81a96b0c7f69a34f3f
