### ISSUE TITLE
CodeFever首页入口在什么地方？

### ISSUE THREAD

**Issue by xiaotangren** [PGYER/codefever#81]
使用从零安装的方式安装在云服务器上.
安装成功之后通过ip进行访问时页面显示
 500 
抱歉服务器有点忙 
[回到CodeFever首页]
请问登陆的入口在什么地方？

**Comment by cubicwork** [comment]
@xiaotangren hi 您好，请确人你的 mysql 服务已经打开，并且可以访问。你可以登录终端尝试访问一下你的数据库，看看服务是否能够访问，并且 codefever_community 表是否存在。如果不存在，请运行 misc/create_db.sh 来创建数据表。 如果问题没有解决请回复此 issue

**Comment by xiaotangren** [comment]
> @xiaotangren你好，请确实你的mysql服务打开，并且可以查看访问。你登录终端尝试访问一下你的数据库，服务是否能够访问，并且如果codefever_community表是否存在。不存在，请运行misc/create_db.sh 来创建数据表。如果没有问题解决请回复此问题

**服务器可以访问远程数据库，并且数据迁移也执行成功了。项目访问首页是依然是 500 服务器繁忙**

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/27838773/162355761-ea0822e0-9785-4765-ad14-6997c7e0d1aa.png">

**项目env.yaml配置如下**

<img width="637" alt="image" src="https://user-images.githubusercontent.com/27838773/162356266-7f3d4812-d227-431a-adac-febe9ed44dd1.png">

**Comment by cubicwork** [comment]
@xiaotangren 您好，您的 yaml 文件格式存在不合法的地方。在 mysql 字段中， 请确保以  `key: value` （ `key:<SP>value` ）的格式来编辑。 注意 `key` 后面的冒号后需要有一个空格来间隔 `value`。

**Comment by xiaotangren** [comment]
> @xiaotangren 您好，您的 yaml 文件格式存在不合法的地方。在 mysql 字段中， 请确保以 `key: value` （ `key:<SP>value` ）的格式来编辑。 注意 `key` 后面的冒号后需要有一个空格来间隔 `value`。

确实是yaml中mysql信息格式出现了问题。
现在可以正常使用了。
非常感谢！
我想删除掉第一个问题中链接的部分，他暴露了我服务器的真实ip。

**Comment by cubicwork** [comment]
@xiaotangren 已帮你删除

**Comment by xiaotangren** [comment]
> @xiaotangren 已帮你删除

ღ( ´･ᴗ･` )比心

**Comment by xiaotangren** [comment]
> @xiaotangren 已帮你删除
ღ( ´･ᴗ･` )比心
