### ISSUE TITLE
请问如何二开前端？

### ISSUE THREAD

**Issue by Drswith** [PGYER/codefever#87]
如题，内部使用一样能加个定制logo，但是不清楚如何修改ui？…

**Comment by cubicwork** [comment]
@Drswith hi, CodeFever 前端项目位于 `www/view` 目录下，项目给予类似于 `create-react-app` 脚手架工具开发。在 `www/view` 下使用 `yarn start` 即可进入开发模式，开发完成后使用 `yarn build` 来打包。 
二次开发需要有前端基础 和 react 开发经验。详细可以参照 https://reactjs.org/docs/getting-started.html 来学习并完成前端工程开发。

**Comment by Drswith** [comment]
build打包完成后还有后续操作吗？比如将打包出来的静态资源移动到某个目录或是其他操作？
codefever需要重新编译吗？

**Comment by cubicwork** [comment]
@Drswith 使用 yarn build 完成后不需要做任何操作。刷新页面后前端使用的就是打包后的资源。

**Comment by Drswith** [comment]
感谢解答！
