### ISSUE TITLE
请问可否在你们社区版本与公有云版本增加自主注销功能吗？

### ISSUE THREAD

**Issue by supermangithu** [PGYER/codefever#88]
你们的公有云版本，包括 （https://codefever.pgyer.com/，https://codefever.cn/）有关CODEFEVER git托管库产品 没有发现有自主注销功能，希望能在近期接下来更新的版本中增加类似于自主注销这种功能。还有在《服务条款》](https://id.pgyer.com/user/service) 和 《隐私声明》](https://id.pgyer.com/user/privacy)同步更新有关自主注销的条款。

**Comment by cubicwork** [comment]
@supermangithu 您好，公有云报班可以注销账户，创建注销账户工单会有专门的客户服务和你对接。 公有云版本共享同一个蒲公英 ID 需要联系客服或创建工单完成注销操作。 感谢您的建议。
