### ISSUE TITLE
无法识别Markdown格式的表格

### ISSUE THREAD

**Issue by xiaolongba** [PGYER/codefever#89]
你好，感谢你们开源的这套系统。基本的日常使用没有问题，其中我们也遇到了 合并 #82 的问题，但此时我们也遇到了Markdown格式表格无法识别，如下：

| 命令 | AT+START_SCAN=<扫描时长>\r\n|
| --- | --- |
| 功能说明 | 执行该命令，开启扫描周边发出Unprovisioned Device Beacon的设备 |
| 参数说明 | **扫描时长**：<br> `如：0005`：表示搜索周围发出unprovisioned Device Beacon的设备5秒钟 <br> |
| 返回值说明 | `+DEV_UUID:` 返回的unprovisioned Device UUID |
| 适用范围 | Provisioner |
| 示例说明 | `AT+START_SCAN=0005\r\n`<br>`+DEV_UUID:73FB210D4AD98F45B2DF93EE71127C68\r\n` |
| 注意 | 扫描时长参数务必是2个字节 |

可以看到，上述的表格是可以被Github识别的，但是一模一样的内容在Codefever是下述这样的：

![image](https://user-images.githubusercontent.com/16135532/169691425-91b5f2f6-90a5-44ec-87bd-bec5e90b183e.png)

能否帮忙看看吗？

谢谢！

**Comment by cubicwork** [comment]
@xiaolongba 您先别着急，我们安排检查。 表格组件应该是可以正常显示的。 表格需要再 表格代码前后 保留一个换行。我们会安排检查。 还有 #82 的问题中你遇到的是 合并时速度过慢的问题么？这块我们需要确认下。

**Comment by xiaolongba** [comment]
> 还有 #82 的问题中你遇到的是 合并时速度过慢的问题么？这块我们需要确认下

就是点合并请求，但是提示合并请求失败，然后刷新一下页面，在合并请求中看已经提交成功了。同意合并也是一样的，首次提示失败，但是再刷新就发现已经合并成功了

**Comment by xiaolongba** [comment]
> 表格需要再 表格代码前后 保留一个换行

这个我试了，仍然无效，你可以看看我原始的markdown内容：
![image](https://user-images.githubusercontent.com/16135532/169741492-3763d38a-648f-42a8-94ea-dadd148020a8.png)

**Comment by cubicwork** [comment]
@xiaoxielun 我们安排人员检查一下，对您造成的不便表示抱歉。如果有更新 我们会更新此 issue

**Comment by cubicwork** [comment]
@xiaolongba 您好关于合并时候出现错误的问题我们提供的解决方案如下：

- 登录 docker shell （如果使用 docker 方式部署）
- 打开 `/usr/local/nginx/conf/nginx.conf` 文件
- 定位到 78 行
- 在 78 后新增一行 `fastcgi_read_timeout 300s;`
- 保存文件
- 运行 `service nginx reload` 重启服务 即可

由于项目较大时 merge 需要耗费更多资源，在 CPU 算力不足时请求可能会超时。

**Comment by xiaolongba** [comment]
> 您好关于合并时候出现错误的问题我们提供的解决方案如下：
> 
> * 登录 docker shell （如果使用 docker 方式部署）
> * 打开 `/usr/local/nginx/conf/nginx.conf` 文件
> * 定位到 78 行
> * 在 78 后新增一行 `fastcgi_read_timeout 300s;`
> * 保存文件
> * 运行 `service nginx reload` 重启服务 即可
> 
> 由于项目较大时 merge 需要耗费更多资源，在 CPU 算力不足时请求可能会超时。

  非常感谢

**Comment by xiaolongba** [comment]
我按照上述的方法尝试了，点合并时仍然 有问题，如下：
![image](https://user-images.githubusercontent.com/16135532/170401703-0a72de27-7d0e-406a-9469-7e7ad4ef0a98.png)

但是你此时在merge quest 那里则看到这个合并请求已经在了，如下：
![image](https://user-images.githubusercontent.com/16135532/170401822-1a6fee87-70db-4f0c-b882-b1ba55855a29.png)

感觉那个延时还是没用。

此外，我还发现一处英文单词拼错了，如下：
![image](https://user-images.githubusercontent.com/16135532/170401950-28812a50-7d92-4387-959d-a59088c7721e.png)

应该是compare and continue

**Comment by cubicwork** [comment]
@xiaolongba  您好 ，我们需要你提供一下大致点击合并按钮到错误出现等待的时长。 瓶邪错误这块我们记录一下，会尽快修改。

**Comment by xiaolongba** [comment]
> 您好 ，我们需要你提供一下大致点击合并按钮到错误出现等待的时长。 瓶邪错误这块我们记录一下，会尽快修改。

好的，我给你提供一段动图的操作：
![codeforever_merge_request](https://user-images.githubusercontent.com/16135532/170428701-c126838f-af2f-45aa-abd3-868d82b2c690.gif)

**Comment by cubicwork** [comment]
@xiaolongba 我看了你的录屏，我们找测试部分尝试复现一下。应该是 提交合并请求 后 应该点 合并 按钮才会进行合并操作。录屏中的在提交过程中出现错误。应该和合并过程没有关系。
可能是 1. 合并方向不正确，已经合并过的 MR 不允许再次提交。
我们先做检查。有什么进展会在此 issue 跟进。

**Comment by cubicwork** [comment]
@xiaolongba  表格显示的问题已经解决了，登录 shell 后 再 /data/www/codefever/ 目录下运行 git pull origin master 即可更新。

0f0eeb6bcc7dd52c34dd1881e853d3fb6ae3438b

**Comment by xiaolongba** [comment]
ok,谢谢。我先试下，到时给你反馈

**Comment by xiaolongba** [comment]
你好，目前可以正常显示了，但是还是有点问题，如下：
![image](https://user-images.githubusercontent.com/16135532/172089197-252e601f-2934-4a92-8d8f-0e42f2a5e9e3.png)

箭头所指的转行转义字符还是无法识别，正常的如下：
![image](https://user-images.githubusercontent.com/16135532/172089299-36434b6f-32d8-49e2-87dd-e9deee0a3c60.png)

**Comment by cubicwork** [comment]
@xiaolongba 您好，您希望 md 中的 html 也应该被转义显示，对吧。我们标记为 feature 来处理。

**Comment by xiaolongba** [comment]
OK,感谢。
