### ISSUE TITLE
GB2312下中文提示错误

### ISSUE THREAD

**Issue by Mn-Simple** [PGYER/codefever#90]
文件编码为GB2312,有中文的情况下提示
不能识别的响应数据，请稍后再试

**Comment by cubicwork** [comment]
@Mn-Simple  我们检查一下

**Comment by cubicwork** [comment]
@Mn-Simple  问题已经修复，可以参照以下文档描述将修复更新到你的安装中。 
https://github.com/PGYER/codefever/blob/master/doc/zh-cn/installation/update.md
