### ISSUE TITLE
centos7如何部署ssh

### ISSUE THREAD

**Issue by 616252396** [PGYER/codefever#93]
容器的秘钥已经部署。
服务器的ssh端口改成23。
服务器的22端口映射到了容器的22端口。
强制改服务器的ssh提示失败。
怎么配置，让可以使用ssh克隆代码？

**Comment by shishirui** [comment]
服务器的ssh端口改成23失败了吗？请提供失败具体报错提示信息。成功更改后，应该就可以直接通过ssh来clone代码了。

**Comment by 616252396** [comment]
服务器的ssh端口改成功了，我配置了域名，http拉取代码可以
 在服务器本地拉取失败  git clone  git@127.0.0.1:wai_bao/git.git 
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
最终想实现在本地可以ssh操作

**Comment by shishirui** [comment]
请检查你是否配置了正确的 ssh key，配置的地址在 http://[你的域名或IP]/settings/sshkey 。

**Comment by 616252396** [comment]
跟这个是一个问题
https://github.com/PGYER/codefever/issues/94

**Comment by cubicwork** [comment]
@616252396 请参照我在 #94 的回复。尝试登录 docker 容易，并重启 SSH 服务。如果问题不能解决请在 #94 问题中继续回复。

**Comment by 616252396** [comment]
可以了，感谢感谢
