### ISSUE TITLE
无法通过ssh的方式clone或者push代码

### ISSUE THREAD

**Issue by NorthCityChen** [PGYER/codefever#94]
通过docker安装的codefever服务端无法通过ssh的方式clone或者push代码

我在我的服务器上以及本机上都通过docker的方式部署了这个项目，http的方式似乎是可用的，但是ssh的方式似乎不能正确的拉取或者推送代码，我尝试过删除known_hosts文件并且重新配置ssh key，但这似乎并不管用

报错信息如下：
```
Cloning into 'kkk'...
kex_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by shishirui** [comment]
请检查你是否配置了正确的 ssh key，配置的地址在 `http://[你的域名或IP]/settings/sshkey` ，并非在 known_hosts 文件中。

**Comment by NorthCityChen** [comment]
> 请检查你是否配置了正确的 ssh key，配置的地址在 `http://[你的域名或IP]/settings/sshkey` ，并非在 known_hosts 文件中。

非常感谢您能在周末回复我的Issue 😄 

我尝试过在官方提供的 https://codefever.pgyer.com/ 上以及官方提供的community版本的demo上进行测试，都是可以正常clone仓库以及push代码的。但是相同的配置下，我通过docker部署的demo上却无法正常使用

**Comment by 616252396** [comment]
我也是，腾讯云服务器，

**Comment by cubicwork** [comment]
@NorthCityChen @616252396  登录到你的 docker 容器上，尝试重启 SSH 服务看看情况有没有好装。 
尝试运行 `service sshd restart `来重启 SSH 服务。

**Comment by NorthCityChen** [comment]
> @NorthCityChen @616252396 登录到你的 docker 容器上，尝试重启 SSH 服务看看情况有没有好装。 尝试运行 `service sshd restart `来重启 SSH 服务。

非常感谢，我重新启动了一下ssh服务，容器的运行就正常了，非常感谢

**Comment by 616252396** [comment]
解决了 ，进入容器重启ssh

**Comment by zouopen** [comment]
我通过进入容器重新启动ssh服务，当似乎并不管用。
端口也是重新设置了。9200:22 9300:80
当我在上传代码时指定了端口，报出异常。异常如下
fatal: unable to access 'http://xxxxx:9200/xxxxxx/BackEnd_UI.git/': Received HTTP/0.9 when not allowed
fatal: unable to access 'http://xxxxxx:9200/xxxxx/BackEnd_UI.git/': Recv failure: Connection was reset
这两种错误都会出现。请帮忙排查一下。谢谢

**Comment by cubicwork** [comment]
@zouopen 您好， -p 设置中我看到了你的 22 端口映射到了 9200 端口, 80 端口被映射到 9300 端口。因此访问 git 服务的资源路径应该接近于以下这两种样式：
 git clone ssh://git@aaa:9200/bbb/ccc.git （ssh 方式）
活
 git clone http://aaa:9300/bbb/ccc.git （http 方式）

**Comment by caiqiaohch** [comment]
我 docker 部署方式，重启了容器中的ssh， 也登录不上去 能发下 ssh_config 和 sshd_config 这2个文件内容么？

**Comment by NorthCityChen** [comment]
> 我 docker 部署方式，重启了容器中的ssh， 也登录不上去 能发下 ssh_config 和 sshd_config 这2个文件内容么？
> 
> d9501f0b9f1c pgyer/codefever-community:latest "/usr/sbin/init" 6 months ago Up 20 hours 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:2222->22/tcp, :::2222->22/tcp codefever
> 
> ssh 方式没次都要求输入密码
> 
> git clone git@xxxip:2222/server/hhh.git 正克隆到 'hhh'... git@xxxip 's password:

这个应该是ssh证书没有配置好吧，我重启了一下codefever容器内的ssh服务就没有问题了
这个项目现在还是比较不稳定，好几次都是他的ssh服务莫名其妙的挂掉了，然后我又得尝试重新连接，就挺麻烦的，现在已经没有用这个了

**Comment by cubicwork** [comment]
@caiqiaohch 你可以登录到 docker 后可以查看 git 用户价目录 ~/.ssh/authorized_keys 文件中是否包含了你的 ssh key。如果已经包含请登录到 管理后台 (/admin) 查看服务状态是否都在 running 状态。如果没有在 running 状态 请参照文档 https://github.com/PGYER/codefever/blob/master/doc/zh-cn/admin/dashboard.md 启动没有在 running 状态的服务即可。

**Comment by cubicwork** [comment]
> > 我 docker 部署方式，重启了容器中的ssh， 也登录不上去 能发下 ssh_config 和 sshd_config 这2个文件内容么？
> > d9501f0b9f1c pgyer/codefever-community:latest "/usr/sbin/init" 6 months ago Up 20 hours 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:2222->22/tcp, :::2222->22/tcp codefever
> > ssh 方式没次都要求输入密码
> > git clone git@xxxip:2222/server/hhh.git 正克隆到 'hhh'... git@xxxip 's password:
> 
> 这个应该是ssh证书没有配置好吧，我重启了一下codefever容器内的ssh服务就没有问题了 这个项目现在还是比较不稳定，好几次都是他的ssh服务莫名其妙的挂掉了，然后我又得尝试重新连接，就挺麻烦的，现在已经没有用这个了

哥们，有问题告诉我们呀，好歹让我们知道我们是怎么被嫌弃的么...

**Comment by NorthCityChen** [comment]
> 

其实主要就是ssh确实不太稳定，每次重启服务器都需要重新进容器重启一下ssh才好使...

其实抛弃这个服务的原因挺多的：

1. ssh 的bug，这个是最致命的
2. 封装的docker镜像，数据不能单独挂载出来，每次更新要进入容器更新？那我如果想把容器删掉重新安装怎么办？我的数据是不是还得进容器复制出来？我希望的是每次更新都是删掉当前的镜像再重新部署
3. 为什么超级管理员不能删除其他的账户？
4. 还有就是，没有支持 CI/CD 功能，这个功能真的太重要了

不过整体来说，这个服务还是有优点的

1. 内存占用真的不多，部署在我的服务器上完全没有感觉
2. 界面真的很清爽简洁，上手也简单，而且非常贴心的适配了小屏幕的设备

如果可以再优化下，把这些问题都解决了，我认为对于个人用户来说，替代 gitee 应该不是太大的问题

**Comment by cubicwork** [comment]
> > 
> 
> 其实主要就是ssh确实不太稳定，每次重启服务器都需要重新进容器重启一下ssh才好使...
> 
> 其实抛弃这个服务的原因挺多的：
> 
> 1. ssh 的bug，这个是最致命的
> 2. 封装的docker镜像，数据不能单独挂载出来，每次更新要进入容器更新？那我如果想把容器删掉重新安装怎么办？我的数据是不是还得进容器复制出来？我希望的是每次更新都是删掉当前的镜像再重新部署
> 3. 为什么超级管理员不能删除其他的账户？
> 4. 还有就是，没有支持 CI/CD 功能，这个功能真的太重要了
> 
> 不过整体来说，这个服务还是有优点的
> 
> 1. 内存占用真的不多，部署在我的服务器上完全没有感觉
> 2. 界面真的很清爽简洁，上手也简单，而且非常贴心的适配了小屏幕的设备
> 
> 如果可以再优化下，把这些问题都解决了，我认为对于个人用户来说，替代 gitee 应该不是太大的问题


 你说的很对 我们会参照你的建议的
