### ISSUE TITLE
紧急求助！

### ISSUE THREAD

**Issue by QiaoTuCodes** [PGYER/codefever#96]
伙计们，为什么我按照安装指令进行docker 镜像安装，命令行如下：
docker run -d --privileged=true --name codefever -p 80:80 -p 22:22 -it pgyer/codefever-community:latest /usr/sbin/init

这是官方推荐的安装指令，但是会返回一个错误信息：

docker: Error response from daemon: Conflict. The container name "/codefever" is already in use by container "865ce374992d568d2050330f5ef46984c698550dfc92a71ab11ba8975ae47603". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

请问该如何处理？

**Comment by cubicwork** [comment]
@QiaoTuCodes  hi 您好 你可以运行一下 `docker container ls `看看是不是已经有一个叫做的 `codefever` 的容器了。 这个错误表示 已经有一个容器叫做 `codefever` 了并且这个`container` 的 `ID` 是 `865ce374992d568d2050330f5ef46984c698550dfc92a71ab11ba8975ae47603` 如果已经有同名容器了 删除掉同名容器即可。
